##Afghanistan
province =
{ id       = 2171
  air_base = { size = 4 current_size = 4 }
}            # Kabul

#Algeria

province =
{ id         = 727
  naval_base = { size = 4 current_size = 4 }
  air_base = { size = 4 current_size = 4 }
}              # Algiers

#Angola


province =
{ id       = 895
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}            # Luanda

 #.#.# Abyssinia 
 
province = { id = 825   # Addis Abeba - North Ethiopia - Ethiopia
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 827   # Gode - Ethiopian Highland - Ethiopia
   landfort = 1 
 } 
 
province = { id = 828   # Harer - Ethiopian Highland - Ethiopia
   landfort = 1 
 } 
 
 #Antigua
 province =
{ id       = 1760
  naval_base = { size = 2 current_size = 2 }
}            # Antigua
 
 #.#.# Albania 
 
province = { id = 359   # Tirana - Albania - Balkan
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 362   # Vlore - Albania - Balkan
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# Argentina 
 
province = { id = 2048   # La Plata - La Plata - Rio de la Plata
   anti_air = 2 
   naval_base = { size = 8 current_size = 8 } 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 2050   # Buenos Aires - La Plata - Rio de la Plata
   anti_air = 3 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 2053   # Buenos Aires - La Plata - Rio de la Plata
   anti_air = 3 
   naval_base = { size = 3 current_size = 6 } 
 }  
 
 #.#.# Australia 
 
province = { id = 1234   # Buna
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1587   # Bougainville
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1602   # Lae
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1604   # Popondetta - Lae - New Guinea
   air_base = { size = 1 current_size = 1 } 
   anti_air = 1 
 } 
 
province = { id = 1605   # Wewak
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1607   # Port Moresby - Port Moresby - New Guinea
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 2 current_size = 2 } 
   anti_air = 1 
 } 
 
province = { id = 1602   # Lae
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1694   # Collie - Perth - Australia
   anti_air = 5 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
   coastalfort = 1 
 } 
 
province = { id = 1697   # Darwin - Darwin - Australia
   anti_air = 5 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1704   # Brisbane - Brisbane - Australia
   anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1706   # Wollongong - Sydney - Australia
   anti_air = 3 
 } 
 
province = { id = 1707   # Canberra - Sydney - Australia
   anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
   coastalfort = 2 
 } 
 
province = { id = 1708   # Melbourne - Melbourne - Australia
   coastalfort = 1 
   anti_air = 3 
 } 
 
province =
{ id         = 1712
  naval_base = { size = 4 current_size = 4 }
    air_base = { size = 4 current_size = 4 }
}              # adelaide 
 
province = { id = 1713   # Robe - Adelaide - Australia
   anti_air = 2 
 } 
 
province = { id = 1724   # Manus
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1725   # Kavieng
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1726   # Rabaul - Rabaul - Bismarck Archipelago
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 2 current_size = 2 } 
   anti_air = 2 
 } 
 
 #.#.# Austria 
 
province = { id = 189   # Innsbruck - Austria - Austria
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 191   # Klagenfurt - Austria - Austria
   anti_air = 1 
 } 
 
province = { id = 195   # Vienna - Austria - Austria
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
 } 
 
 #Bangladesh
 province =
{ id       = 1445
  naval_base = { size = 4 current_size = 4 }
}            # Chittagong

province =
{ id       = 1449
  air_base = { size = 4 current_size = 4 }
}            # Comilla

#Belarus


province =
{ id       = 599
  air_base = { size = 10 current_size = 10 }
}            # Minsk
 
 #.#.# Belgium 
 
province = { id = 114   # Bruges - Flanders - Benelux
   naval_base = { size = 3 current_size = 3 } 
   anti_air = 1 
 } 
 
province = { id = 115   # Antwerpen - Flanders - Benelux
   air_base = { size = 3 current_size = 3 } 
   naval_base = { size = 10 current_size = 10 } 
   anti_air = 2 
 } 
 
province = { id = 116   # Brussels - Flanders - Benelux
   air_base = { size = 6 current_size = 6 } 
   anti_air = 1 
 } 
 
province = { id = 108   # Liege - Wallonia - Benelux
   landfort = 2 
   anti_air = 2 
 } 
 
province = { id = 894   # Matadi - Angolan Coast - Central Africa
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #Bosnia
 
 province =
{ id       = 356
  naval_base = { size = 2 current_size = 2 }
}            # Mostar

province =
{ id       = 355
  air_base = { size = 2 current_size = 2 }
}            # Sarajevo

#Botswana
province =
{ id         = 870
   air_base = { size = 1 current_size = 1 }
}
 
 #.#.# Bolivia 
 
province = { id = 2020   # Nuestra Senora de La Paz - La Paz - Andes
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.# Brazil 
 
province = { id = 2057   # Curitiba - Sao Paulo - Brazilian Highlands
   anti_air = 1 
 } 
 
province = { id = 2058   # Porto Alegre - Sao Paulo - Brazilian Highlands
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 2059   # Sao Paulo - Sao Paulo - Brazilian Highlands
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 2067   # Goiania - Brasilia - Brazilian Highlands
   anti_air = 2 
 } 
 
province = { id = 2075   # Rio de Janeiro - Rio de Janeiro - Brazilian Highlands
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
 
 #Burma
 
 province =
{ id       = 1410
  naval_base = { size = 2 current_size = 2 }
}            

province =
{ id       = 1415
  air_base = { size = 4 current_size = 4 }
}

 #.#.# Bulgaria 
 
province =
{ id       = 321
  naval_base = { size = 4 current_size = 4 }
  air_base = { size = 4 current_size = 4 }
}            # Varna
 
province = { id = 325   # Burgas - Bulgaria - Balkan
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 #.#.# Canada 
 
province = { id = 2089   # Vancouver - British Columbia - Western Canada
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 2104   # Calgary - Alberta - Western Canada
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 2106   # Winnipeg - Manitoba - Canada
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 2108   # Ottawa - Ontario - Canada
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 2111   # Toronto - Ontario - Canada
   anti_air = 1 
 } 
 
province = { id = 2119   # Montreal - Quebec - Eastern Canada
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 2132   # Halifax - Nova Scotia - Eastern Canada
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 #Croatia
 province =
{ id       = 352
  naval_base = { size = 2 current_size = 2 }
}            # Split

 #.#.# Chile 
 
province = { id = 2023   # Santiago de Chile - Chile - Andes
   anti_air = 2 
   naval_base = { size = 8 current_size = 8 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# China com 
 
province = { id = 1247   # Beijing - Hebei - China
   air_base = { size = 5 current_size = 5 }
   rocket_test = { size = 2 current_size = 2 }  
 } 
  
province = { id = 1365   # Haikou - Guangdong - China
   anti_air = 2 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1367   # Naoming - Guangdong - China
   naval_base = { size = 5 current_size = 5 } 
 } 
 
province = { id = 1369   # Guangzhou - Guangdong - China
   air_base = { size = 3 current_size = 3 } 
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 province = { id = 1331 naval_base = { size = 5 current_size = 5 } } # Yantai

province = { id = 1346 naval_base = { size = 10 current_size = 10 } } # Ningbo

province = { id = 1264 nuclear_reactor = { size = 7 current_size = 7 } } # Lanzhou

province = { id = 1279 air_base = { size = 10 current_size = 10 } } # Nanchong

province = { id = 1338 naval_base = { size = 10 current_size = 10 } air_base = { size = 10 current_size = 10 } } # shanghai

province = { id = 1380 air_base = { size = 10 current_size = 10 } } # Qiqihar

province = { id = 1281 air_base = { size = 10 current_size = 10 } } # Urumqi

province = { id = 1289 air_base = { size = 8 current_size = 8 } } # Lhasa
 
 
province = { id = 1297   # Chengdu - Sichuan - China
   air_base = { size = 3 current_size = 3 } 
 } 
 
 province = { id = 1328   #  Quingdao - ? - China 
   naval_base = { size = 4 current_size = 4 } 
 } 

province = { id = 1330   # Jinan - Shandong - China
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1345   # Hangzhou - Zhejiang - China
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1352   # Nanchang - Jiangxi - China
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1358   # Fuzhou - Fujian - China
   air_base = { size = 1 current_size = 1 } 
 } 
 
 #.#.# Columbia 
 
province = { id = 1986   # Barranquilla - Panaman Ridge - Grand Colombia
   anti_air = 2 
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province =
{ id       = 1991
  naval_base = { size = 4 current_size = 4 }
  air_base = { size = 2 current_size = 2 }
}            # Medellin

#Congo

province =
{ id       = 899
  air_base = { size = 2 current_size = 2 }
}            # Kinhasa 
 
 #.#.# Costa Rica 
 
province = { id = 2081   # San Jose - Nicaragua - Central America
   anti_air = 1 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 #.#.# Cuba 
 
province =
{ id       = 1776
  naval_base = { size = 2 current_size = 2 }
    air_base = { size = 4 current_size = 4 }
}            # Havanna

#Cyprus
province =
{ id       = 388
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 1 current_size = 1 }
}            # Cyprus
 
 #.#.# Czech Republic

province =
{ id       = 207
  air_base = { size = 4 current_size = 4 }
}            # Prague 
 
 #.#.# Denmark 
 
province = { id = 218   # Frederikshavn - Denmark - Denmark
   anti_air = 1 
   naval_base = { size = 1 current_size = 1 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 294   # Copenhagen - Denmark - Denmark
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
 province =
{ id       = 220
  air_base = { size = 4 current_size = 4 }
}            # Århus

#Djibouti
province =
{ id         = 833
  naval_base = { size = 2 current_size = 2 }
}              # Djibouti

#Ecuador
province =
{ id       = 2042
  naval_base = { size = 2 current_size = 2 }
  air_base = { size = 2 current_size = 2 }
}            # Quito
 
 #.#.# Dominican Republic 
 
province = { id = 1780   # Ciudad Trujillo - Hispaniola - Caribbean
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #.#.# Ecuador 
 
province = { id = 2040   # Santiago de Guayaquil - Quito - Andes
   naval_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 2042   # San Francisco de Quito - Quito - Andes
   anti_air = 2 
   air_base = { size = 1 current_size = 1 } 
 } 
 
 #.#.# Egypt 
 
province = { id = 787   # Cairo - Delta - Egypt
   anti_air = 2 
   air_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 789   # Alexandria - Delta - Egypt
   anti_air = 5 
   air_base = { size = 7 current_size = 7 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 
province = { id = 791   # Port Said - Suez Channel Area - Egypt
   anti_air = 2 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #Eritrea
 province =
{ id       = 817
    air_base = { size = 2 current_size = 2 }
}            # Asmarra

 #.#.# Estonia 
 
province = { id = 270   # Tallinn - Estonia - Baltic States
   anti_air = 2 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 2 current_size = 2 } 
 }

#Ethiopia

province =
{ id       = 825
  air_base = { size = 2 current_size = 2 }
}            # Addis Abbas 
 
 #.#.# Finland 
 
province = { id = 517   # Petsamo - Lapland - Finland
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 520   # Oulu - Central Finland - Finland
   air_base = { size = 2 current_size = 2 } 
   anti_air = 1 
 } 
 
province = { id = 524   # Turku - Oesterbotten - Finland
   coastalfort = 2 
   anti_air = 2 
   naval_base = { size = 6 current_size = 6 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 525   # Helsinki - South Finland - Finland
   coastalfort = 1 
   anti_air = 3 
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 526   # Ahvenanmaa - Oesterbotten - Finland
   coastalfort = 1 
 } 
 
province = { id = 527   # Tampere - South Finland - Finland
   anti_air = 2 
   air_base = 4 
 } 
 
province = { id = 528   # Mikkeli - South Finland - Finland
   anti_air = 2 
   air_base = 5 
 } 
 
province = { id = 529   # Kouvola - South Finland - Finland
   anti_air = 1 
 } 
 
province = { id = 531   # Viipuri - Karelia - Finland
   landfort = 8 
   anti_air = 4 
   air_base = 1 
   coastalfort = 2 
 } 
 
province = { id = 532   # Sortavala - Karelia - Finland
   anti_air = 6 
 } 
 
province = { id = 535   # Murmansk - Kola - White Sea Tundra
   air_base = 3 
 } 
 
#.#.# France 
 
province = { id = 37   # Brest - Brittany - France
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 40   # Saint-Nazaire - Brittany - France
   anti_air = 2 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 43   # Cherbourg - Normandy - France
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 44   # Caen - Normandy - France
   anti_air = 1 
 } 
 
province = { id = 51   # Dunkirk - Pas de Calais - France
   naval_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 52   # Lille - Pas de Calais - France
   air_base = { size = 10 current_size = 10 } 
   anti_air = 1 
 } 
 
province = { id = 55   # Paris - Paris - France
   anti_air = 5 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 57   # Nantes - Loire - France
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 66   # Orleans - Loire - France
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 68   # Bordeaux - Aquitaine - France
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 69   # La Rochelle - Aquitaine - France
   anti_air = 4 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 72   # Chateauroux - Limousin_Auvergne - France
   anti_air = 1 
 } 
 
province = { id = 77   # Toulouse - Pyrenees_Languedoc - France
   air_base = { size = 10 current_size = 10 } 
   nuclear_reactor = 6
}            
 
province = { id = 86   # Toulon - Alpes_Provence - France
   anti_air = 3 
   naval_base = { size = 10 current_size = 10 } 
 } 
  
 
province = { id = 89   # Marseille - Alpes_Provence - France
   naval_base = { size = 5 current_size = 5 }
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
 
province = { id = 104   # Metz - Lorraine_Alsace - France
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
    } 
 
province = { id = 105   # Colmar - Lorraine_Alsace - France
   anti_air = 2 
   } 
 
province = { id = 107   # Strasbourg - Lorraine_Alsace - France
   anti_air = 2 
   } 

 province = { id = 1582   # Espiritu Santo
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 #Georgia
 
province =
{ id       = 709
  air_base = { size = 2 current_size = 2 }
}            # Batum
 
 #.#.# Germany 
  
province = { id = 134   # Stuttgart - Baden_Wurttemberg - Germany
    anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 137   # Kassel - Hessen - Germany
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 138   # Frankfurt/Main - Hessen - Germany
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 145   # Essen - Westphalen - Germany
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 147   # Wilhelmshaven - Hannover_Magdeburg - Germany
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 
province = { id = 151   # Lubeck - Holstein_Mecklemburg - Germany
   anti_air = 1 
 } 
 
province = { id = 152   # Kiel - Holstein_Mecklemburg - Germany
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 153   # Rostock - Holstein_Mecklemburg - Germany
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 154   # Hamburg - Holstein_Mecklemburg - Germany
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 163   # Berlin - Brandenburg - Germany
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 167   # Breslau - Silesia - Germany
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 169   # Magdeburg - Sachsen - Germany
   anti_air = 2 
 } 
 
province = { id = 170   # Leipzig - Sachsen - Germany
   anti_air = 1 
 } 
 
province = { id = 177   # Nuremberg - Bavaria - Germany
   anti_air = 1 
 } 
 
province = { id = 179   # Munich - Bavaria - Germany
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
 } 
 
#.#.# Greece 
 
province = { id = 365   # Thessaloniki - Thrace - Balkan
    anti_air = 2 
 } 

province =
{ id         = 373
  air_base = { size = 4 current_size = 4 }
}              # corinth 
 
province = { id = 377   # Athens - Attica - Balkan
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 382   # Irakleio - Greek Island - Balkan
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
#.#.# Guatemala 
 
province = { id = 2088   # Ciudad de Guatemala - Central Rainforests - Central America
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# Haiti 
 
province = { id = 1781   # Port-au-Prince - Hispaniola - Caribbean
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# Holland 
 
province = { id = 118   # Eindhoven - Netherlands - Benelux
   anti_air = 2 
 } 
 
province = { id = 122   # Amsterdam - Netherlands - Benelux
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 125   # Rotterdam - Netherlands - Benelux
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 #.#.# Honduras 
 
province = { id = 2085   # Tegucigalpa - Nicaragua - Central America
   anti_air = 1 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# Hungary 
 
province = { id = 284   # Budapest - Eastern Hungary - Hungary
   anti_air = 2 
   air_base = { size = 8 current_size = 8 } 
 } 
 
 #Iceland
 province =
{ id         = 1
  naval_base = { size = 2 current_size = 2 }
    air_base = { size = 8 current_size = 8 }
}              # Reykjavik

#India

province =
{ id         = 1447
  naval_base = { size = 8 current_size = 8 }
  air_base = { size = 10 current_size = 10 }
}              # Calcutta

province =
{ id         = 1504
  naval_base = { size = 8 current_size = 8 }
  air_base = { size = 10 current_size = 10 }
}              # Madurai

province =
{ id         = 1517
  naval_base = { size = 6 current_size = 6 }
}              # Bombay

province =
{ id       = 1459
  air_base = { size = 10 current_size = 10 }
}           

province =
{ id       = 1461
  air_base = { size = 8 current_size = 8 }
}            # New Delhi


province =
{ id         = 1502
      nuclear_reactor = 6
}            # Bangalore

#Indonesia

province =
{ id         = 1647
  naval_base = { size = 6 current_size = 6 }
    air_base = { size = 4 current_size = 4 }
}              # Batavia

province =
{ id         = 1653
  naval_base = { size = 4 current_size = 4 }
    air_base = { size = 2 current_size = 2 }
}              # soerabaja

#IRAN

province =
{ id         = 1089
  naval_base = { size = 6 current_size = 6 }
}              # ahvaz

province =
{ id         = 1086
    air_base = { size = 8 current_size = 8 }
}              # Esfahan

province =
{ id         = 1092
    air_base = { size = 4 current_size = 4 }
}              # Mashhad

province =
{ id         = 1090
    air_base = { size = 6 current_size = 6 }
}    

province =
{ id         = 1085
    air_base = { size = 6 current_size = 6 }
}   

province =
{ id         = 1087
    air_base = { size = 6 current_size = 6 }
}             

province =
{ id         = 1090
      nuclear_reactor = 4
}            # Busheer
 
 #.#.# Iraq 
 
province = { id = 1032   # Basrah - Iraq - Middle East
   anti_air = 2 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1033   # El Hillah - Iraq - Middle East
   anti_air = 1 
 } 
 
 province =
{ id         = 1034
  air_base = { size = 6 current_size = 6 }
}              # Bagdadh
 
province = { id = 1035   # Kut - Iraq - Middle East
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 #.#.# Ireland 
 
province = { id = 34   # Dublin - Eire - Ireland
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 4 current_size = 4 } 
  } 
   province = { id = 31   # Cork - Eire - Ireland
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 #Israel
 
 
province =
{ id         = 1011
  naval_base = { size = 4 current_size = 4 }
    air_base = { size = 8 current_size = 8 }
}              # Haifa

province =
{ id         = 1008
    air_base = { size = 8 current_size = 8 }
  rocket_test = { size = 2 current_size = 2 }
}              # Tel-Aviv

province =
{ id         = 1010
      nuclear_reactor = 6
}            # Eliat

 
 #.#.# Italy 
 
 

province = {
	id = 393
	air_base = { size = 10 current_size = 10 }
} #Ghedi

province = {
	id = 420
	air_base = { size = 6 current_size = 6 }
} # foggia
 
province = { id = 396   # Genoa - North Italy - Italy
   ic = { size = 4 current_size = 4 }
   naval_base = { size = 10 current_size = 10 }  
 } 
 
province = { id = 398   # Turin - North Italy - Italy
   ic = { size = 5 current_size = 5 }
 } 
 
province = { id = 400   # Venice - North Italy - Italy
   ic = { size = 4 current_size = 4 }
   air_base = { size = 6 current_size = 6 } 
 } 

province = { id = 401   # Trento - North Italy - Italy
 ic = { size = 2 current_size = 2 }
 }
 
province = 
 { id = 404   # Trieste - North Italy - Italy
 
   naval_base = { size = 2 current_size = 2 }  
 } 
 
province = { id = 408   # Parma - Appennine Ridge - Italy
   ic = { size = 3 current_size = 3 }
   air_base = { size = 4 current_size = 4 }
 } 
 
 
province = { id = 411   # Bologna - Appennine Ridge - Italy
   ic = { size = 4 current_size = 4 }
   air_base = { size = 6 current_size = 6 }
 } 
 
province = { id = 412   # Ancona - Appennine Ridge - Italy
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 419   # Rome - Central Italy - Italy
   ic = { size = 4 current_size = 4 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 421   # Naples - South Italy - Italy
   ic = { size = 4 current_size = 4 }
   naval_base = { size = 7 current_size = 7 } 
 } 
 
province = { id = 422   # Taranto - South Italy - Italy
   ic = { size = 3 current_size = 3 }
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 
province = { id = 426   # Bari - South Italy - Italy
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 430   # Palermo - Sicilian Gap - Italy
   ic = { size = 1 current_size = 1 }
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 433   # Siracuse - Sicilian Gap - Italy
   naval_base = { size = 4 current_size = 4 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 434   # Cagliari - Ligurian Islands - Italy
   air_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# Japan 
 
province = { id = 1550   # Yokohama - Tohoku - Japan
   anti_air = 2 
 } 
 
province = { id = 1551   # Niigata - Tohoku - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1552   # Tokyo - Tohoku - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1553   # Osaka - Honshu - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1554   # Hiroshima - Honshu - Japan
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1557   # Nagoya - Honshu - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1558   # Kyoto - Honshu - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1559   # Matsuyama - Kyushu_Shikoku - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1560   # Nagasaki - Kyushu_Shikoku - Japan
   anti_air = 2 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1563   # Southern Okinawa - Ryukyusland - Japan
   anti_air = 2 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
 #Asia Pacific
 
province = { id = 1661   # Iwo Jima - Bonin - Asian Pacific
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1662   # Chichi Jima - Bonin - Asian Pacific
   anti_air = 2 
 } 
 
province = { id = 1663   # Motoyama - Bonin - Asian Pacific
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1665   # Ponape - Carolinese - Asian Pacific
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1666   # Kusaie - Carolinese - Asian Pacific
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1667   # Truk - Carolinese - Asian Pacific
   anti_air = 5 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1668   # Woleai - Carolinese - Asian Pacific
   anti_air = 3 
   air_base = { size = 1 current_size = 1 }
 } 

province = { id = 1669   # Yap
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1670   # Peleliu
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
  
province = { id = 1672   # Minami Torishima
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 1 current_size = 1 } 
 } 

province = 
 { id = 1674   # Bikini - Marshalls - Asian Pacific
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = 
 { id = 1675   # Eniwetok - Marshalls - Asian Pacific
   anti_air = 5 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1676   # Kwajalein - Marshalls - Asian Pacific
   anti_air = 5 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1677   # Majuro
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1681   # Wotje
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1685   # Saipan
   anti_air = 5 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1686   # Pagan - North Marianes - Asian Pacific
   anti_air = 3 
 } 
 
 #Jordan
 
province = {
	id = 1022
	air_base = { size = 4 current_size = 4 }
} #Amman

#Kazakhstan

province = {
	id = 1110
	air_base = { size = 3 current_size = 3 }
} #Turgai

province = {
	id = 502
	air_base = { size = 2 current_size = 2 }
}

#Kenya

province = {
	id = 841
	air_base = { size = 2 current_size = 2 }
} #Nairobi

#Kuwait

province = {
	id = 1041
	air_base = { size = 10 current_size = 10 }
	naval_base = { size = 10 current_size = 10 }
} #Kuwait City
 
#.#.# Latvia 
 
province = { id = 264   # Riga - Latvia - Baltic States
   anti_air = 1 
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #Lebanon
 
 
province = {
	id = 1019
	air_base = { size = 2 current_size = 2 }
} #Beirut

#Libya

province = {
	id = 750
	naval_base = { size = 4 current_size = 4 }
	air_base = { size = 4 current_size = 4 }
} #Tripoli

 
#.#.# Liberia 
 
province = { id = 969   # Monrovia - Guinean Coast - West Africa
   anti_air = 1 
   naval_base = { size = 2 current_size = 2 } 
 } 
 
 #Lithuania 
 
province = {
	id = 261
	naval_base = { size = 2 current_size = 2 }
} #Memel

province = {
	id = 258
	air_base = { size = 2 current_size = 2 }
} #Wilno 

#Malaysia

province = {
	id = 1436
	naval_base = { size = 6 current_size = 6 }
} #Kuantan

province = {
	id = 1438
	air_base = { size = 4 current_size = 4 }
} #Kuala Lumpur

#Malta
province = {
	id = 429
	naval_base = { size = 8 current_size = 8 }
} #Malta
 
 #.#.# Syria 
 
province = { id = 1019   # Beirut - Lebanon_Syria - Middle East
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 2 current_size = 2 } 
 } 
  
province = {
	id = 1021
	naval_base = { size = 4 current_size = 4 }
} #Aleppo

province = {
	id = 1017
	air_base = { size = 10 current_size = 10 }
} #Homs
 
#.#.# Mexico 
 
province = { id = 1973   # Leon de los Aldama - Mexico City - Mexico
   anti_air = 1 
 } 
 
province = { id = 1972   # Acapulco de Juarez - Mexico City - Mexico
   anti_air = 1 
 } 
 
province = { id = 1974   # Mexico City - Mexico City - Mexico
   anti_air = 2 
 } 
 
province = { id = 1970   # Oaxaca de Juarez - Vera Cruz - Mexico
   anti_air = 2 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = {
	id = 1966
	naval_base = { size = 4 current_size = 4 }
} #Merida

province = {
	id = 1980
	naval_base = { size = 4 current_size = 4 }
} #Culiacrn

province = {
	id = 1978
	air_base = { size = 4 current_size = 4 }
}# Durango

#Moldova
province = {
	id = 304
	air_base = { size = 2 current_size = 2 }
}# Chisinev
 
#.#.# Mongolia 
 
province = {
	id = 1124
	air_base = { size = 2 current_size = 2 }
}# Ulan Bator

#Montenegro

province = {
	id = 332
	naval_base = { size = 2 current_size = 2 }
} #Podgorica

#Mozambique

province = {
	id = 857
	naval_base = { size = 4 current_size = 4 }
} #Beira
 
 #.#.# NewZealand 
 
province = { id = 1721   # Wellington - New Zealand - Australia
   anti_air = 2 
   naval_base = { size = 5 current_size = 5 } 
   air_base = { size = 3 current_size = 3 } 
 } 

province = { id = 1731   # Apia
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 #Nigeria
 
province =
{ id       = 929
  naval_base = { size = 2 current_size = 2 }
}            # Lagos

province =
{ id       = 939
    air_base = { size = 4 current_size = 4 }
}            # Kaduna

 
#.#.# Nicaragua 
 
province = { id = 2080   # Managua - Nicaragua - Central America
   naval_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Norway 
 
 
province = {
	id = 488
	naval_base = { size = 6 current_size = 6 }
} #Haakonsvern - Bergen

province = {
	id = 494
	air_base = { size = 4 current_size = 4 }
}# Bodr - Mo i Rana
 
province = { id = 483   # Oslo - Southern Norway - Norway
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
   coastalfort = 3 
 } 
 
province = { id = 491   # Alesund - Southcentral Norway - Norway
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 5 current_size = 5 } 
   coastalfort = 3 
 } 
 
province = { id = 495   # Narvik - Central Norway - Norway
   anti_air = 1 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Oman 
 
province = { id = 1052   # Masqat - Yemenite Mountains - Middle East
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 }
 
 #Pakistan
 
 
province = {
	id = 1533
	naval_base = { size = 6 current_size = 6 }
} #Karachi

province = {
	id = 1529
	air_base = { size = 8 current_size = 8 }
} #Sukkur

province = {
	id = 1537
	air_base = { size = 4 current_size = 4 }
} #Peshwar

province = {
	id = 1529
	nuclear_reactor = 6
} #Sukkur

#.#.# Panama 
 
province = { id = 2078   # Ciudad de Panama - Panaman Ridge - Central America
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
 } 
 
 #Papua new guinea
 
province = {
	id = 1607
	naval_base = { size = 2 current_size = 2 }
} #Port Moresby

 #.#.# Paraquay 
 
province = { id = 2047   # Nuestra Senora de la Asuncion - Asuncion - Gran Chaco
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# Persia 
 
province = { id = 1091   # Gameroon - East Persia - Persia
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
#.#.# Peru 
 
province = {
	id = 2016
	naval_base = { size = 4 current_size = 4 }
	air_base = { size = 4 current_size = 4 }
} #Lima
 
#.#.# Philipines 
 
province = { id = 1565   # Manila - Luzon - Philippines
   anti_air = 2 
   naval_base = { size = 8 current_size = 8 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1566   # Cabanatuan - Luzon - Philippines
   anti_air = 4 
   air_base = { size = 5 current_size = 5 } 
   naval_base = { size = 2 current_size = 2 } 
 } 

province = {
	id = 1570
	air_base = { size = 6 current_size = 6 }
} #Aparri
 
 #.#.# Poland 
  
province = {
	id = 181
	naval_base = { size = 2 current_size = 2 }
} #Gdansk
 
province = { id = 222   # Torun - Poznan - Poland
   anti_air = 2 
 } 
 
province = 
 { id = 224   # Poznan - Poznan - Poland
   anti_air = 4 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 225   # Bydgoszcz - Poznan - Poland
   anti_air = 1 
 } 
 
province = { id = 226   # Gdynia - Poznan - Poland
   anti_air = 2 
   naval_base = { size = 8 current_size = 8 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 227   # Czestochowa - Poznan - Poland
   air_base = { size = 3 current_size = 3 } 
   anti_air = 3 
 } 
 
province = { id = 228   # Siedlce - Warsaw - Poland
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 230   # Plock - Warsaw - Poland
   anti_air = 1 
 } 
 
province = { id = 232   # Warsaw - Warsaw - Poland
   anti_air = 2 
   air_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 235   # Krakow - Krakow - Poland
   anti_air = 2 
 } 
 
province = { id = 240   # Tarnopol - Lvov - Poland
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 252   # Suwalki - Polotsk - Poland
   anti_air = 1 
 } 
 
#.#.# Portugal 
 
province = { id = 476   # Lisbon - Portugal - Portugal
   anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = {
	id = 481
	naval_base = { size = 4 current_size = 4 }
 #Oporto
 } 
 
province = { id = 995   # The Azores - The Azores - Portugal
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 4 current_size = 4 } 
 } 

#PRK

province = { id = 1227 naval_base = { size = 6 current_size = 6 } air_base = { size = 10 current_size = 10 } } # Hamhung

province = { id = 1221 air_base = { size = 10 current_size = 10 } } # Pyongyang

province = { id = 1224 nuclear_reactor = 6 } # Sinuiju

#Qatar
province = {
	id = 1038
	air_base = { size = 2 current_size = 2 }
} #Doha

#REp congo

province = {
	id = 907
	air_base = { size = 1 current_size = 1 }
}
 
#.#.# Romania 
 
province = { id = 306   # Ismail - Bessarabia - Romania
   anti_air = 1 
 } 
 
province = { id = 307   # Dobrich - South Romania - Romania
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = {
	id = 313
	naval_base = { size = 4 current_size = 4 }
} #Constanta

province = {
	id = 311
	air_base = { size = 4 current_size = 4 }
}# Ploesti
 
province = { id = 316   # Bucharest - South Romania - Romania
   anti_air = 2 
   air_base = { size = 5 current_size = 5 } 
 } 
 
#.#.# San Salvador 
 
province = { id = 2079   # San Salvador - Nicaragua - Central America
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 #.#.# Saudi Arabia 
 
province = { id = 1048   # Medina - Hedjaz - Middle East
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
 
province = {
	id = 1044
	naval_base = { size = 2 current_size = 2 }
} #Jiddah

province = {
	id = 1040
	naval_base = { size = 4 current_size = 4 }
} #Dammam

province = {
	id = 1045
	air_base = { size = 10 current_size = 10 }
} #Riyadh

#Serbia

province = {
	id = 338
	air_base = { size = 4 current_size = 4 }
} #Beograd

#Singapore

province = {
	id = 1432
	naval_base = { size = 4 current_size = 4 }
	air_base = { size = 4 current_size = 4 }
} #Singapore

#Slovakia

province = {
	id = 211
	air_base = { size = 2 current_size = 2 }
} #Banska Bystrica

#Somalia

province = {
	id = 836
	naval_base = { size = 7 current_size = 7 }
	air_base = { size = 2 current_size = 2 }
} #Mogadishu

#Somaliland

province = {
	id = 832
	naval_base = { size = 2 current_size = 2 }
}
 
#.#.# Siam 
 
province = { id = 1424   # Nakhon Sawan - Siam - Indochine
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
#.#.# South Africa 
 
province = { id = 872   # Pretoria - Transvaal_Natal - South Africa
   anti_air = 3 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 876   # Johannesburg - Transvaal_Natal - South Africa
   anti_air = 3 
 } 
 
province = { id = 880   # Cape Town - Cape - South Africa
   anti_air = 4 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 881   # Port Elizabeth - Cape - South Africa
   anti_air = 1 
 } 
 
province = { id = 882   # Swakopmund - Nambia - Southwest Africa
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 1 current_size = 1 } 
 } 
  
#.#.# Russia
 
province = { id = 535   # Murmansk - Kola - White Sea Tundra
   anti_air = 4 
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 542   # Arkhangelsk - Arkhangelsk - Northern Russia
   anti_air = 4 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 550   # Kingisepp - Novgorod - Western Russia
   landfort = 1 
} 
 
province = { id = 552   # Gdov - Novgorod - Western Russia
   landfort = 1 
 } 
 
province = { id = 553   # Leningrad - Leningrad - Russia
   anti_air = 6 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
   landfort = 5 
   coastalfort = 5 
 } 
 
province = { id = 561   # Staraya Russa - Pskov - Western Russia
   anti_air = 1 
 } 
 
province = { id = 563   # Torzhok - Velikiye Luki - Russia
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 564   # Opochka - Pskov - Western Russia
   landfort = 1 
 } 
 
province = { id = 566   # Pskov - Pskov - Western Russia
   air_base = { size = 6 current_size = 6 } 
   landfort = 1 
 } 
 
province = { id = 572   # Moscow - Moscow - Russia
   air_base = { size = 10 current_size = 10 } 
   landfort = 5 
   anti_air = 4 
 } 
 
province = { id = 585   # Kozelsk - Ryazan - Russia
   air_base = { size = 3 current_size = 3 } 
   anti_air = 1 
 } 
 
province = { id = 587   # Klintsy - Smolensk - Western Russia
   anti_air = 2 
 } 
 
province = { id = 589   # Smolensk - Smolensk - Western Russia
   anti_air = 3 
 } 
 
province = { id = 590   # Vitebsk - Minsk - Belarus
   air_base = { size = 2 current_size = 2 } 
   anti_air = 2 
 } 
 
province = { id = 592   # Borisov - Minsk - Belarus
   landfort = 2 
} 
 
province = { id = 593   # Polotsk - Minsk - Belarus
   landfort = 1 
 } 
 
province = { id = 595   # Mozyr - Mozyr - Belarus
   landfort = 2 
 } 
 
province = { id = 596   # Slutsk - Rogachev - Belarus
   landfort = 2 
 } 
province = { id = 597   # Luban - Mozyr - Belarus
   air_base = { size = 2 current_size = 2 } 
   landfort = 2 
 } 
 
province = { id = 600   # Mogilev - Rogachev - Belarus
   air_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 604   # Kursk - Kursk - Southern Russia
   air_base = { size = 5 current_size = 5 } 
 } 
 
province = { id = 614   # Proskurov - Transnistria - Ukraine
   landfort = 2 
 } 
 
province = { id = 616   # Novograd-Volynsky - Transnistria - Ukraine
   landfort = 2 
} 
 
province = { id = 618   # Kamenets-Podolsky - Transnistria - Ukraine
   landfort = 1 
 } 
 
province = { id = 626   # Odessa - Odessa - Ukraine
   air_base = { size = 4 current_size = 4 } 
   anti_air = 3 
 } 
 
province = { id = 629   # Poltava - Poltava - Ukraine
   anti_air = 2 
 } 
 
province = { id = 631   # Mariupol - Dnepropretovsk - Ukraine
   air_base = { size = 4 current_size = 4 } 
   anti_air = 2 
 } 
 
province = { id = 636   # Kharkov - Kharkov - Ukraine
   air_base = { size = 2 current_size = 2 } 
   anti_air = 1 
 } 
 
province = { id = 639   # Dzhankoy - Krim - Ukraine
   air_base = { size = 2 current_size = 2 } 
 } 
 
 province = {
	id = 644
	naval_base = { size = 4 current_size = 4 }
} #Rostov
 
province = { id = 648   # Rossosh - Belgorod - Southern Russia
   anti_air = 1 
 } 
 
province = { id = 653   # Pavlovsk - Tambov - Southern Russia
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 663   # Stalingrad - Stalingrad - Southern Russia
   air_base = { size = 4 current_size = 4 } 
   landfort = 5 
   anti_air = 3 
 } 
 
province = { id = 666   # Engels - Engels - Eastern Russia
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 669   # Saratov - Penza - Southern Russia
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 706   # Astrakhan - Astrakhan - Kaukasus
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 708   # Kutaisi - Georgien - Kaukasus
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1130   # Berezniki - Perm - Urals
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1134   # Orenburg - Orenburg - Eastern Russia
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1138   # Omsk - Omsk - Novosibirsk
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1143   # Biysk - Novosibirsk - Novosibirsk
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1164   # Ust-Kut - Irkutsk - Irkutsk
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 1176   # Blagoveshchensk - Amur - Far East Siberia
   anti_air = 2 
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1185   # Sovetskaya Gavan - Khabarovsk - Far East Siberia
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1191   # Vladivostok - Primorski - Far East Siberia
   anti_air = 5 
   naval_base = { size = 10 current_size = 10 } 
   air_base = { size = 10 current_size = 10 } 
   landfort = 1 
   coastalfort = 3 
 } 
 
province = { id = 1194   # Lesozavodsk - Primorski - Far East Siberia
   anti_air = 2 
 } 

province = { id = 654 # Voronezh
   air_base = { size = 2 current_size = 1 }
 }
province = { id = 588 # Bryansk
   air_base = { size = 4 current_size = 3 }
 }
province = { id = 589 # Smolensk
   air_base = { size = 2 current_size = 2 }
 }
 province = { id = 611 # Zhitomir
   air_base = { size = 1 current_size = 1 }
 }
 province = { id = 628 # Kirovograd
   air_base = { size = 2 current_size = 1 }
 }
 province = { id = 630 # Zaporozhye
   air_base = { size = 2 current_size = 2 }
 }
 province = { id = 1169 # Chita
   air_base = { size = 2 current_size = 2 }
 }
 province = { id = 1190 # Khabarovsk
   air_base = { size = 4 current_size = 3 }
 }
 province = { id = 644 # Rostov na Donu
   air_base = { size = 2 current_size = 2 }
 } 
 
 #South Korea
 
province = {
	id = 1232
	naval_base = { size = 8 current_size = 8 }
	air_base = { size = 8 current_size = 8 }
}# Busan

province = {
	id = 1228
	air_base = { size = 6 current_size = 6 }
	rocket_test = { size = 2 current_size = 2 }
} #Seoul

 
#.#.# Spain 


province = {
	id = 440
	naval_base = { size = 8 current_size = 8 }
	air_base = { size = 4 current_size = 4 }
} #Barcelona

province = {
	id = 444
	naval_base = { size = 4 current_size = 4 }
} #Oviedo

province = {
	id = 448
	air_base = { size = 4 current_size = 4 }
} #Valladolid
 
province = { id = 436   # Tarragona - Catalonia - Spain
   anti_air = 2 
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 441   # Coruna - Cantabric Chain - Spain
   anti_air = 2 
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 460   # Madrid - Central Spain - Spain
   anti_air = 3 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 464   # Valencia - Levant - Spain
   anti_air = 2 
   naval_base = { size = 3 current_size = 3 } 
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 473   # Cadiz - West Andalucia - Spain
   naval_base = { size = 5 current_size = 7 } 
 } 
 
province = { id = 474   # Sevilla - West Andalucia - Spain
   anti_air = 2 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 475   # Palma de Mallorca - Baleares - Spain
   anti_air = 2 
   naval_base = { size = 7 current_size = 7 } 
   air_base = { size = 4 current_size = 4 } 
 } 

#Sudan

province = {
	id = 813
	naval_base = { size = 2 current_size = 2 }
} #Port Sudan

province = {
	id = 810
	air_base = { size = 4 current_size = 4 }
} #Khartoum
 
#.#.# Sweden 
 
province = { id = 2153   # Gothenburg - Goetaland - Sweden
   naval_base = { size = 5 current_size = 5 } 
   air_base = { size = 3 current_size = 3 } 
 } 
 
province = { id = 2159   # Stockholm - Oestra Svealand - Sweden
   anti_air = 5 
   naval_base = { size = 5 current_size = 5 } 
   air_base = { size = 3 current_size = 3 } 
 } 
  
province = {
	id = 2160
	air_base = { size = 4 current_size = 4 }
} #Skovde

province = {
	id = 2165
	air_base = { size = 2 current_size = 2 }
}# Umel
 
#.#.# Switzerland 
 
province = { id = 389   # Zurich - Switzerland - Switzerland
     anti_air = 3 
} 
 
province = { id = 390   # Lugano - Switzerland - Switzerland
   landfort = 4 
   anti_air = 3 
 } 
 
province = { id = 391   # Geneva - Switzerland - Switzerland
   landfort = 5 
   anti_air = 3 
} 
 
province ={ id = 392   # Bern - Switzerland - Switzerland
   anti_air = 5 
   air_base = { size = 4 current_size = 4 } 
    } 
	
#Taiwan
	
province = {
	id = 1362
	naval_base = { size = 10 current_size = 10 }
	air_base = { size = 8 current_size = 8 }
} #Taipei

#Thailand

province = {
	id = 1423
	naval_base = { size = 6 current_size = 6 }
	air_base = { size = 6 current_size = 6 }
} #Bangkok

#Tunisia

province = {
	id = 747
	naval_base = { size = 2 current_size = 2 }
	air_base = { size = 2 current_size = 2 }
} #Tunis
 
#.#.# Turkey 
 
 
province = {
	id = 1067
	naval_base = { size = 10 current_size = 10 }
} #trabson

province = { id = 1075   # Ankara - Central Turkey - Anatolia
   anti_air = 4 
   air_base = { size = 6 current_size = 6 } 
 } 
 
province = { id = 1076   # Izmit - Bosporus - Anatolia
   anti_air = 4 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
 province = { id = 1054   # ANTAYA - Bosporus - Anatolia
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 #Turkmenistan
 
province = {
	id = 1097
	air_base = { size = 4 current_size = 4 }
} #Ashgabat

#UAE

province = {
	id = 1039
	naval_base = { size = 4 current_size = 4 }
	air_base = { size = 4 current_size = 4 }
} #Dubai

#Uganda

province = {
	id = 844
	air_base = { size = 1 current_size = 1 }
} #Kampala

#Ukraine

province = {
	id = 641
	naval_base = { size = 10 current_size = 10 }
} #Sevastopol

province = {
	id = 617
	air_base = { size = 4 current_size = 4 }
}# Kiev
 
#.#.# United Kingdom 

province = {
	id = 24
	air_base = { size = 8 current_size = 8 }
}# Birmingham

province = {
	id = 4
	air_base = { size = 10 current_size = 10 }
} #

province = {
	id = 7
	air_base = { size = 10 current_size = 10 }
} #

province = {
	id = 12
	air_base = { size = 10 current_size = 10 }
} #

province = {
	id = 16
	air_base = { size = 6 current_size = 6 }
} #

province = {
	id = 13
	air_base = { size = 6 current_size = 6 }
} #

province = {
	id = 28
	air_base = { size = 6 current_size = 6 }
} #

province = {
	id = 18
	nuclear_reactor = 6
} #Sheffield
  
 province = { id = 23   # Plymouth - West England - England
   anti_air = 2 
   naval_base = { size = 10 current_size = 10 } 
    } 
 
province = { id = 25   # Norwich - East England - England
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
    } 
 
province = { id = 26   # Dover - East England - England
   anti_air = 5 
 } 
 
province = { id = 27   # Portsmouth - East England - England
   anti_air = 6 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
province = { id = 28   # Oxford - East England - England
   anti_air = 2 
 } 

province = { id = 11   # Glasgow - South Scotland - Scotland
   naval_base = { size = 5 current_size = 5 }
 }
province = { id = 12   # Edinburgh - South Scotland - Scotland
   naval_base = { size = 4 current_size = 4 }
 }
 
province = { id = 348   # Gibraltar - West Andalucia - Spain
   anti_air = 6 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 10 current_size = 10 } 
   landfort = 6 
 } 
 
province = { id = 1771   # The Bahamas - Bahamas Islands - Caribbean
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1773   # The Bermudas - Bermuda - Caribbean
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1997   # Georgetown - Guayana - Grand Colombia
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 2045   # Falkland Islands - The Falklands - Patagonia
   anti_air = 2 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 5 current_size = 5 } 
 } 
 
 
#.#.# Urugay 
 
province = { id = 2052   # Montevideo - La Plata - Rio de la Plata
   anti_air = 1 
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
#.#.# Usa 
 
province = { id = 889   # Balboa - Panaman Ridge - Central America
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = {
	id = 1041
	naval_base = { size = 10 current_size = 10 }
	air_base = { size = 10 current_size = 10 }
	supplypool = 5000
	oilpool = 2000
} #Kuwait

province = {
	id = 1563
	naval_base = { size = 8 current_size = 8 }
	air_base = { size = 8 current_size = 8 }
} #Okinawa

province = { id = 1673   # Wake - Marcus_Wake - Asian Pacific
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1683   # Guam - North Marianes - Asian Pacific
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1733   # Pago Pago
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1734   # Pearl Harbor - Hawaii - American Pacific
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1735   # Kauai
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1736   # Hawaii
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1737   # Maui
   air_base = { size = 2 current_size = 2 } 
 } 
 
province = { id = 1738   # Johnston
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1739   # Midway
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1747   # Palmyra
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1751   # Baker Island
   air_base = { size = 1 current_size = 1 } 
 } 
 
province = { id = 1778   # Guantanamo Bay Naval Base - Cuba - Caribbean
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 1787   # Concord - New Hampshire - Northeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1789   # Boston - Massachussets - Northeast US
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1792   # Syracuse - New York - Northeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1795   # New York - New York - Northeast US
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1805   # Philadelphia - Pennsylvania - Northeast US
   anti_air = 2 
 } 
 
province = { id = 1806   # Pittsburgh - Pennsylvania - Northeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1809   # Washington - Maryland_Delaware - Northeast US
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1812   # Norfolk - Virginia - Northeast US
   anti_air = 4 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1820   # Lexington - Kentucky - Northeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1832   # Chicago - Illinois - Midwest US
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1833   # Saint Louis - Missouri - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1839   # Milwaukee - Wisconsin - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1845   # Detroit - Michigan - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1846   # Rochester - Minnesota - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1855   # Fargo - North Dakota - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1859   # Lincoln - Nebraska - Midwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1874   # Seattle - Washington - Northwest US
   anti_air = 1 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1878   # Portland - Oregon - Northwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1886   # San Diego - California - Southwest US
   anti_air = 1 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1887   # Los Angeles - California - Southwest US
   anti_air = 3 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 1888   # Sacramento - California - Southwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1889   # San Francisco - California - Southwest US
   anti_air = 3 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1896   # Salt Lake City - Utah - Southwest US
   anti_air = 1 
   air_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1901   # Tucson - Arizona - Southwest US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1906   # Santa Fe - New Mexico - Southcentral US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1908   # Denver - Colorado - Southcentral US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1913   # Oklahoma City - Oklahoma - Southcentral US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1922   # Corpus Christi - Texas - Southcentral US
   anti_air = 1 
   air_base = { size = 6 current_size = 6 } 
   naval_base = { size = 8 current_size = 8 } 
 } 
 
province = { id = 1928   # Houston - Texas - Southcentral US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 province = {
	id = 1930
	air_base = { size = 10 current_size = 10 }
} 

province = { id = 1940   # Memphis - Tennessee - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1944   # Mobile - Alabama - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1952   # Jacksonville - Florida - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1953   # Miami - Florida - Southeast US
   anti_air = 1 
   air_base = { size = 10 current_size = 10 } 
   naval_base = { size = 10 current_size = 10 } 
 } 
 
province = { id = 1955   # Atlanta - Georgia - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1960   # Charleston - South Carolina - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
province = { id = 1962   # Charlotte - North Carolina - Southeast US
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
 } 
 
 
province = { id = 2142   # Anchorage - Alaska - Alaska
   anti_air = 1 
   air_base = { size = 4 current_size = 4 } 
   naval_base = { size = 4 current_size = 4 } 
 } 
 
 province = {
	id = 2171
	air_base = { size = 4 current_size = 4 }
} #Kabul

province = { id = 2174   # Attu Island - Alaskan Archipelago - Alaska
   anti_air = 1 
   air_base = { size = 2 current_size = 2 } 
   naval_base = { size = 1 current_size = 1 } 
 } 
 
 #Uzbekistan
 province = {
	id = 1103
	air_base = { size = 2 current_size = 2 }
} #Tashkent
 
#.#.# Venezuela 
 
province = { id = 1988   # Maracaibo - Maracaibo - Grand Colombia
   anti_air = 2 
   air_base = { size = 1 current_size = 1 } 
   naval_base = { size = 6 current_size = 6 } 
 } 
 
province = {
	id = 1993
	naval_base = { size = 4 current_size = 4 }
	air_base = { size = 4 current_size = 4 }
} #Caracas 

#Vietnam

province = {
	id = 1399
	naval_base = { size = 4 current_size = 4 }
} #Nha Trang

province = {
	id = 1399
	air_base = { size = 4 current_size = 4 }
} #Ho Chi Mihn City

province = {
	id = 1395
	air_base = { size = 6 current_size = 6 }
}# Hanoi

#Yeman

province = {
	id = 1053
	naval_base = { size = 2 current_size = 2 }
	air_base = { size = 2 current_size = 2 }
} #Aden

#Zimbawe

province = {
	id = 867
	air_base = { size = 2 current_size = 2 }
} #Harare

 