 
 ############################## 
 # Country definition for U33 # 
 ############################## 
  
 country = 
 {  tag                    = U33 
   # Resource Reserves 
energy                 = 300
metal                  = 150
rare_materials         = 75
   oil                    = 500 
   supplies               = 500 
   money                  = 10 
   manpower               = 0 
   capital                = 1670 
   diplomacy = 
   {  relation = {  tag = BEL value = 200  } 
     relation = {  tag = DEN value = 100  } 
     relation = {  tag = FIN value = 100  } 
     relation = {  tag = FRA value = 120  } 
     relation = {  tag = GER value = -50  } 
     relation = {  tag = HOL value = 150  } 
     relation = {  tag = IRE value = 75  } 
     relation = {  tag = NOR value = 100  } 
     relation = {  tag = SWE value = 100  } 
    } 
   SpyInfo                = {  country = "U33" NumberOfSpies = 3  } 
   nationalprovinces      = {  1670 1671  } 
   ownedprovinces         = {  1670 1671  } 
   controlledprovinces    = {  1670 1671  }  
   techapps            = {
                                        #Industry:
                                        5010
                                        5020
                                        5030
                                        5040
                                        5050
                                        5070
                                        5090
                                        #Army Equip:
                                        2400
                                        2200
                                        2500
                                        2600
                                        2800
                                        #Army Org:
                                        1300
                                        1900
                                        1260
                                        1980
                                        #Army Doc:
                                        6100
                                        6110
                                        6160
                                        6010
                                        6020
                                        6600
                                        6610
                                        6910
                                        #Secret Tech:
                                        7330
                        }
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 9 
     political_left    = 1 
     freedom           = 9 
     free_market       = 8 
     professional_army = 1 
     defense_lobby     = 2 
     interventionism   = 1 
    } 
   
  } 
 
