 country = { 
  tag       	 = REB
  
  nationalprovinces    = {  } 
  ownedprovinces       = {  } 
  controlledprovinces  = { 974 984 985 } 
  capital	= 984
  
landunit = { 
        id = { type = 24100 id = 1 } 
        location = 984
        division = { 
            id = { type = 24100 id = 2 } 
            #name =
            type = militia
			model = 0 
			strength = 5
			locked = yes
        	} 
	}			 
} 
 