# #############################
# Country definition for U96 #
# #############################

country = {
	tag = U96
	# Resource Reserves
	energy = 200
	metal = 200
	rare_materials = 200
	oil = 200
	supplies = 200
	money = 10
	manpower = 70
	capital = 978
	diplomacy = { }
	nationalprovinces      = {  977 978 980 983  } 
   ownedprovinces         = {  977 978 980 983  } 
   controlledprovinces    = {  977 978 980 983  } 
	techapps = {
		# Industry
		5010
		5020
		5030
		5040
		5050
		5060
		5070
		5080
		5090
		# Army Equip:
		2000
		2010
		2300
		2400
		2200
		2210
		2500
		2600
		2700
		2800
		2810
		# Land Docs
		6010
		6020
		6910
		6100
		6110
		6120
		6160
		6600
		6610
		# Army Org
		1000
		1010
		1500
		1300
		1260
		1980
		1900
		# Secret Tech:
		7330
	}
	policy = {
		date = { year = 0 month = march day = 0 }
		democratic = 9
		political_left = 5
		free_market = 6
		freedom = 3
		professional_army = 1
		defense_lobby = 2
		interventionism = 4
	}
	# #####################################
	# ARMY
	# #####################################
	landunit = {
		id = { type = 12205 id = 1 }
		location = 978
		name = "Senegal Army Corps"
		division = {
			id = { type = 12205 id = 2 }
			name = "1st Infantry Division"
			strength = 100
			type = motorized
			model = 1
		}
		division = {
			id = { type = 12205 id = 3 }
			name = "2nd Infantry Division"
			strength = 100
			type = motorized
			model = 1
		}
	}
}
