# #############################
# Country definition for USA #
# #############################

country = {
	tag = USA
	# Resource Reserves
	nuke = 180
	energy = 10000
	metal = 8000
	rare_materials = 5000
	oil = 10000
	supplies = 8000
	money = 500
	manpower = 250
	transports = 1000
	escorts = 50
	capital = 1809
	diplomacy = {
		relation = {
			tag = U91 #Kuwait
			value = 200
			guaranteed = { day = 22 month = september year = 2003 }
			access = yes
		}
		relation = {
			tag = CAN
			value = 200
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = { tag = MEX value = 50 }
		relation = { tag = CUB value = -100 }
		relation = {
			tag = PAN
			value = 100
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = { tag = COL value = 150 access = yes }
		relation = { tag = VEN value = -50 }
		relation = { tag = BRA value = 100 }
		relation = { tag = CHL value = 50 }
		relation = { tag = ARG value = 50 }
		relation = {
			tag = ICL
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = DEN
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = NOR
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = { tag = SWE value = 150 }
		relation = { tag = FIN value = 150 }
		relation = {
			tag = EST
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = LAT
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = LIT
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = { tag = BLR value = -100 }
		relation = { tag = UKR value = -50 }
		relation = {
			tag = POL
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = GER
			value = 100
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = FRA
			value = 100
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = HOL
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = BEL
			value = 100
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = ENG
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = IRE
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = SPA
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = POR
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = CZE
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = SLO
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = AUS
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = HUN
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = ITA
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = ROM
			value = 100
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = BUL
			value = 90
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = GRE
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = TUR
			value = 100
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = SLV
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = { tag = CRO value = 50 }
		relation = { tag = SER value = -20 }
		relation = { tag = U23 value = 150 access = yes }
		relation = { tag = BOS value = 50 access = yes }
		relation = { tag = GEO value = 150 access = yes }
		relation = { tag = U70 value = 150 access = yes }
		relation = { tag = U95 value = 150 access = yes }
		relation = { tag = AZB value = 150 }
		relation = { tag = SYR value = -150 }
		relation = { tag = PER value = -150 }
		relation = { tag = IRQ value = -200 }
		relation = {
			tag = SAU
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = OMN
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = U52
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = U51
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = { tag = U56 value = -150 }
		relation = { tag = KAZ value = 50 }
		relation = { tag = UZB value = 100 access = yes }
		relation = {
			tag = KYG
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = { tag = TAJ value = 150 access = yes }
		relation = { tag = TRK value = -20 access = yes }
		relation = { tag = PAK value = 90 access = yes }
		relation = { tag = IND value = 100 }
		relation = { tag = CHC value = 50 }
		relation = { tag = PRK value = -170 }
		relation = {
			tag = KOR
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = JAP
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = CHI
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = { tag = BUR value = -150 }
		relation = {
			tag = PHI
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = NZL
			value = 150
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = {
			tag = AST
			value = 200
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
		relation = { tag = HON value = 50 access = yes }
		relation = { tag = MOR value = 50 access = yes }
		relation = { tag = EGY value = 70 access = yes }
		relation = { tag = SIA value = 70 }
		relation = { tag = U72 value = 120 }
		relation = { tag = INO value = 70 }
		relation = {
			tag = ISR
			value = 170
			access = yes
			guaranteed = { day = 22 month = march year = 2003 }
		}
	}
	SpyInfo = { country = "CHC" NumberOfSpies = 4 }
	SpyInfo = { country = "PRK" NumberOfSpies = 2 }
	SpyInfo = { country = "JAP" NumberOfSpies = 2 }
	SpyInfo = { country = "FRA" NumberOfSpies = 3 }
	SpyInfo = { country = "VEN" NumberOfSpies = 5 }
	SpyInfo = { country = "MEX" NumberOfSpies = 5 }
	SpyInfo = { country = "BRA" NumberOfSpies = 3 }
	SpyInfo = { country = "BLR" NumberOfSpies = 3 }
	SpyInfo = { country = "RUS" NumberOfSpies = 4 }
	SpyInfo = { country = "IND" NumberOfSpies = 2 }
	SpyInfo = { country = "PAK" NumberOfSpies = 3 }
	SpyInfo = { country = "PER" NumberOfSpies = 4 }
	SpyInfo = { country = "IRQ" NumberOfSpies = 1 }
	SpyInfo = { country = "GER" NumberOfSpies = 2 }
	SpyInfo = { country = "GUA" NumberOfSpies = 5 }
	SpyInfo = { country = "CUB" NumberOfSpies = 4 }
	SpyInfo = { country = "COL" NumberOfSpies = 3 }
	SpyInfo = { country = "ARG" NumberOfSpies = 2 }
	SpyInfo = { country = "BUR" NumberOfSpies = 1 }
	SpyInfo = { country = "EGY" NumberOfSpies = 2 }
	SpyInfo = { country = "UZB" NumberOfSpies = 3 }
	SpyInfo = { country = "GEO" NumberOfSpies = 4 }
	SpyInfo = { country = "UKR" NumberOfSpies = 4 }
	SpyInfo = { country = "KAZ" NumberOfSpies = 2 }
	SpyInfo = { country = "ISR" NumberOfSpies = 3 }
	SpyInfo = { country = "SAU" NumberOfSpies = 2 }
	SpyInfo = { country = "CAN" NumberOfSpies = 1 }
	SpyInfo = { country = "KYG" NumberOfSpies = 2 }
	nationalprovinces      = {  1809 1953 1949 1948 1952 1951 1950 1947 1956 1954 1955 1960 1958 1963 1961   
      1962 1964 1813 1812 1814 1818 1815 1816 1817 1808 1807 1801 1797 1791 1795 1793    
      1792 1805 1803 1804 1790 1787 1788 1784 1785 1789 1796 1826 1806   
      1810 1811 1820 1819 1942 1943 1940 1939 1936 1937 1944 1931 1825 1821 1842 1845 1802   
      1957 1828 1934 1930 1929 1932 1918 1915 1925 1836 1833 1830 1829 1832 1839   
      1838 1841 1843 1834 1837 2140 2145 2144 2146 2151 1846 1850 1855 1856 1858 1857 1859   
      1860 1914 1913 1919 1910 1911 1924 1928 1926 1920 1921 1922   
      1905 1906 1904 1900 1901 1902 1898 1896 1907 1908 1897 1909  
     1868 1866 1862 1869 1865 1871 1873 1875 1876 1874  
      1877 1878 1882 1879 1880 1895 1893 1892 1899 1886 1887 1883  
     1888 1889 1884 2141  2142 2147 2143 2139  2174
     1923  
     1831 1847 1935 1945 1885 1872 1863 2150 1864 1778       
    1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  
                              }  
    ownedprovinces         = {  1953  1949  1948  1952  1951  1950  1947  1956  1954    1955  1960  1958  1963    1961  1962  1964  1813  1812    1814  1818 1815 1816 1817  1809   
                               1808  1807  1801  1797  1791  1795  1793    1792  1805  1803  1804    1790    1787  1788  1784  1785    1789  1796  1826  1806   
                               1810  1811  1820  1819  1942  1943  1940   1939 1936 1937  1944  1931  1825  1821  1842  1845  1802  1957  1828  1934  1930  1929 1932  1918  1915     
                               1925    1836  1833  1830  1829  1832  1839  1838  1841  1843  1834  1837   2145 2144 2146 2151  1846  1850        1855  1856  1858  1857  1859   
                               1860    1914  1913    1919  1910  1911    1924  1928  1926  1920   1921  1922   1905  1906  1904  1900    1901   
                               1902  1898  1896  1907  1908  1897  1909  1868  1866      1862        1869    1865    1871    1873 1875 1876  1874     
                               1877  1878  1882    1879  1880    1895  1893    1892  1899  1886  1887  1883  1888  1889  1884  2141   2140  2142 2147 2143  2139     
                                         1923      1765    1736  1737  1735    1739  1734  1738  1673 1683   
                 1747  
               1733 1751 1745  
               1778 1831  
               1872 1863 2150 1864 1847 1935 1945 1885  2174
         1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  1684 1685 1686
                              }  
    controlledprovinces    = {  1953  1949  1948  1952  1951  1950  1947  1956  1954   1955  1960  1958  1963    1961  1962  1964  1813  1812    1814  1818 1815 1816 1817  1809   
                               1808  1807  1801  1797  1791  1795  1793    1792  1805  1803  1804   1790    1787  1788  1784  1785    1789  1796  1826  1806   
                               1810  1811  1820  1819  1942  1943  1940    1939 1936 1937  1944  1931  1825  1821  1842  1845  1802  1957  1828  1934  1930  1929 1932  1918  1915     
                               1925    1836  1833  1830  1829  1832  1839  1838  1841  1843  1834  1837   2145 2144 2146 2151  1846  1850        1855  1856  1858  1857  1859   
                               1860    1914  1913    1919  1910  1911    1924  1928  1926  1920    1921  1922   1905  1906  1904  1900    1901   
                               1902  1898  1896  1907  1908  1897  1909  1868  1866      1862        1869    1865    1871    1873 1875 1876  1874    
                               1877  1878  1882    1879  1880    1895  1893    1892  1899  1886  1887  1883  1888  1889  1884  2141    2140  2142 2147 2143  2139     
                                         1923      1765    1736  1737  1735    1739  1734  1738  1673 1683  1747  
                1733 1751 1745  2174
               1778 1831  
               1872 1863 2150 1864 1847 1935 1945 1885  
         1890 1891 1894 1881  
  1870 1861 1903 1851 1916 1927 1912 1852 1853 1854 1867 1849 1917 1933 1835 1840 1848 1844 1822 1823 1827 1941 1946 1959 1800  
  1794 1824 1798 1799 1786 1938  1684 1685 1686
                }
	claimedprovinces = { 1733 #American Samoa
	} 
	techapps = {
		# Industry
		5010 5020 5030
		5040 5050 5060
		5070 5080 5090
		5110 5120 5130
		5140 5150 5160
		5170 5180 5190
		5210 5220 5230
		5240 5250 5260
		5270 5280 5290
		# Army Equip
		2200 2210 2220
		2230 2300 2310
		2320 2330 2400
		2410 2420 
		2500 2510 2520
		2530 2600 2610
		2620 2630 2700
		2710 2720 2730
		2800 2810 2820
		2830 2000 2010
		2050 2110 2120
		# Army Org
		1980 1970 1260
		1270 1900 1910
		1920 1930 1500
		1510 1520 1530
		1400 1410 1420
		1430 1300 1310
		1320 1330 1200
		1210 1220 1230
		1600 1650 1610
		1660 1800 1810
		1820 1700 1710
		1720 1000 1010
		1110 1120
		# Aircraft
		4800 4810 4820
		4700 4710 4720
		4750 4760 4770
		4000 4010 4020
		4030 4100 4110
		4120 4130 4640
		4650 4660 4600
		4610 4620 4550
		4570 4500 4510
		4520 4200 4210
		4220 4900 4910
		4920 4400 4410
		4420 4300 4310
		4320
		# Land Docs
		6930 6010 6030
		6050 6070 6080
		6600 6630 6700
		6730 6100 6110
		6120 6130 6140
		6150 6160 6170
		6200 6210 6220
		6230 6240 6250
		6260 6270 6300
		6310 6320 6330
		6340 6350 6360
		6370 
		# Air Docs
		9040 9510 9520
		9530 9540 9050
		9060 9070 9080
		9090 9100 9110
		9120 9130 9140
		9150 9160 9170
		9180 9190 9200
		9210 9220 9230
		9240 9250 9260
		9270 9280 9450
		9460 9470
		# Secret Weapons
		7010 7020 7030
		7040 7050 7060
		7070 7080 7180
		7190 7200 7210
		7240 7330 7310
		7320 7270 7280
		7290 7300 7140
		 7250 7260
		7100 7110 7120
		# Navy
		3000 3010 3020
		3100 3110 3120
		3130 3200 3210
		3220 3300 3310
		3320 3590 3600
		3610 3620 3800
		3810 
		3820 3830 3850
		3860 3870 3880
		3900 3910 3920
		# Navy Doctrines
		8900 8910 8920
		8930 8950 8960
		8970 8980 8400
		8410 8420 8000
		8010 8020 8500
		8510 8520 8100
		8110 8120 8130
		8600 8610 8620
		8630 8200 8210
		8220 8700 8710
		8720 8300 8310
		8320 8330 8800
		8810 8820 8830
	}
	blueprints = { 4040 4140 7150 7340 }
	policy = {
		date = { year = 0 month = march day = 0 }
		democratic = 10
		political_left = 2
		free_market = 8
		freedom = 8
		professional_army = 6
		defense_lobby = 5
		interventionism = 9
	}
	# #####################################
	# ARMY
	# #####################################
        landunit = {
		id = { type = 22400 id = 1 }
		location = 1041
		name = "CENTCOM"
		division = {
			id = { type = 22400 id = 2 }
			name = "3rd Army"
			strength = 100
			type = hq
			model = 2
		}     
	}
        landunit = {
		id = { type = 22400 id = 3 }
		location = 1041
		name = "V Corps"
                division = {
			id = { type = 22400 id = 4 }
			name = "2nd Armored Cavalry Regiment" # brigade size
			strength = 100
			type = light_armor
			model = 8
		}
		division = {
			id = { type = 22400 id = 5 }
			name = "3rd Armored Cavalry Regiment"  # brigade size
			strength = 100
			type = light_armor
			model = 8
		}
		division = {
			id = { type = 22400 id = 6 }
			name = "3rd Infantry Division"
			strength = 100
			type = infantry
			model = 3
			extra = heavy_armor
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 7 }
			name = "4th Infantry Division"
			strength = 100
			type = infantry
			model = 3
			extra = heavy_armor
			brigade_model = 2
		}
                division = {
			id = { type = 22400 id = 8 }
			name = "2nd Bde. - 82nd Airborne Division"
			strength = 100
			type = paratrooper
			model = 16
		}     
	}
        landunit = {
		id = { type = 22400 id = 9 }
		location = 1041
		name = "101st Airborne Division" # airmobile
		division = {
			id = { type = 22400 id = 10 }
			name = "1st Bde. - 101st Airborne Division"
			strength = 100
			type = militia
			model = 3
		}
		division = {
			id = { type = 22400 id = 11 }
			name = "2nd Bde. - 101st Airborne Division"
			strength = 100
			type = militia
			model = 3
		}
		division = {
			id = { type = 22400 id = 12 }
			name = "3rd Bde. - 101st Airborne Division"
			strength = 100
			type = militia
			model = 3
		}
	}
        landunit = {
		id = { type = 22400 id = 13 }
		location = 1041
		name = "I Marine Expeditionary Force"
		division = {
			id = { type = 22400 id = 14 }
			name = "1st Marine Division"
			strength = 100
			type = marine
			model = 17
			extra = heavy_armor
			brigade_model = 3
		}
	}
        landunit = {
		id = { type = 22400 id = 15 }
		location = 1041
		name = "SETAF"
		division = {
			id = { type = 22400 id = 16 }
			name = "173rd Airborne Brigade"
			strength = 100
			type = paratrooper
			model = 17
		}
	}
	landunit = {
		id = { type = 22400 id = 17 }
		location = 1032
		name = "XVIII Airborne Corps"
		division = {
			id = { type = 22400 id = 18 }
			name = "11th Armored Cavalry Regiment"  # brigade size 
			strength = 100
			type = light_armor
			model = 7
		}
                division = {
			id = { type = 22400 id = 19 }
			name = "3rd Bde. - 82nd Airborne Division"
			strength = 100
			type = paratrooper
			model = 16
		}
	}
        landunit = {
		id = { type = 22400 id = 20 }
		location = 1926
		name = "SOUTHCOM"
		division = {
			id = { type = 22400 id = 21 }
			name = "6th Army"
			strength = 100
			type = hq
			model = 2
			extra = sp_artillery
			brigade_model = 3
		}
	}
        landunit = {
		id = { type = 22400 id = 22 }
		location = 1925
		name = "III Corps"
		division = {
			id = { type = 22400 id = 23 }
			name = "1st Cavalry Division"
			strength = 100
			type = armor
			model = 17
			extra = heavy_armor
			brigade_model = 0
		}
	}
        landunit = {
		id = { type = 22400 id = 24 }
		location = 2142
		name = "US Army Alaska"
		division = {
			id = { type = 22400 id = 25 }
			name = "172nd Infantry Brigade"  # arctic training
			strength = 100
			type = mechanized
			model = 3
		}
	}
        landunit = {
		id = { type = 22400 id = 26 }
		location = 138
		name = "EUCOM"
		division = {
			id = { type = 22400 id = 27 }
			name = "7th Army"   # the divisions should be under V corps, but corp's command is in iraq
			strength = 100
			type = hq
			model = 2
			extra = sp_artillery
			brigade_model = 3
		}
		division = {
			id = { type = 22400 id = 28 }
			name = "1st Armored Division"
			strength = 100
			type = armor
			model = 17
			extra = heavy_armor
			brigade_model = 3
		}
		division = {
			id = { type = 22400 id = 29 }
			name = "1st Infantry Division"
			strength = 100
			type = infantry
			model = 3
			extra = heavy_armor
			brigade_model = 2
		}
	}
        landunit = {
		id = { type = 22400 id = 31 }
		location = 1734
		name = "USARPAC"
		division = {
			id = { type = 22400 id = 32 }
			name = "PACOM"
			strength = 100
			type = hq
			model = 2
			extra = sp_artillery
			brigade_model = 3
		}
		division = {
			id = { type = 22400 id = 33 }
			name = "25th Infantry Division"
			strength = 100
			type = motorized
			model = 3
		}
	}
	landunit = {
		id = { type = 22400 id = 34 }
		location = 1228 
		name = "8th Army"
		division = {
			id = { type = 22400 id = 35 }
			name = "8th Army"
			strength = 100
			type = hq
			model = 2
			extra = sp_artillery
			brigade_model = 3
		}
		division = {
			id = { type = 22400 id = 36 }
			name = "2nd Infantry Division"
			strength = 100
			type = infantry
			model = 3
			extra = heavy_armor
			brigade_model = 2
		}
	}
	landunit = {
		id = { type = 22400 id = 37 }
		location = 1931
		name = "Marine Force Reserve"
		division = {
			id = { type = 22400 id = 38 }
			name = "4th Marine Division"
			strength = 100
			type = marine
			model = 16
			extra = heavy_armor
			brigade_model = 2
		}
	}
	landunit = {
		id = { type = 22400 id = 39 }
		location = 1563
		name = "III Marine Expeditionary Force"
		division = {
			id = { type = 22400 id = 40 }
			name = "3rd Marine Division"
			strength = 100
			type = marine
			model = 17
			extra = heavy_armor
			brigade_model = 2
		}
	}
	landunit = {
		id = { type = 22400 id = 41 }
		location = 1963
		name = "II Marine Expeditionary Force"
		division = {
			id = { type = 22400 id = 42 }
			name = "2nd Marine Division"
			strength = 100
			type = marine
			model = 17
			extra = heavy_armor
			brigade_model = 2
		}
	}
	landunit = {
		id = { type = 22400 id = 43 }
		location = 2171
		name = "10th Mountain Division"
		division = {
			id = { type = 22400 id = 44 }
			name = "1st Bde. - 10th Mountain Division"
			strength = 100
			type = bergsjaeger
			model = 14
			extra = police
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 45 }
			name = "2nd Bde. - 10th Mountain Division"
			strength = 100
			type = bergsjaeger
			model = 14
			extra = police
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 46 }
			name = "3rd Bde. - 10th Mountain Division"
			strength = 100
			type = bergsjaeger
			model = 14
			extra = police
			brigade_model = 2
		}
	}
	landunit = {
		id = { type = 22400 id = 47 }
		location = 2169
		name = "Task Force Devil"
		division = {
			id = { type = 22400 id = 48 }
			name = "1st Bde. - 82nd Airborne Division"
			strength = 100
			type = paratrooper
			model = 16
		}     
	}
	# ##################################
	# US ARMY NATIONAL GUARD
	# ##################################
	landunit = {
		id = { type = 22400 id = 49 }
		location = 1908
		name = "Colorado National Guard"
		division = {
			id = { type = 22400 id = 50 }
			name = "7th Infantry Division"
			strength = 100
			type = motorized
			model = 2
			}
	}
        landunit = {
		id = { type = 22400 id = 51 }
		location = 1961
		name = "North Carolina National Guard"
		division = {
			id = { type = 22400 id = 52 }
			name = "24th Infantry Division"
			strength = 100
			type = infantry
			model = 2
		}
	}
        landunit = {
		id = { type = 22400 id = 53 }
		location = 1806
		name = "Pennsylvania National Guard"
		division = {
			id = { type = 22400 id = 54 }
			name = "28th NG Infantry Division"
			strength = 100
			type = infantry
			model = 2
			}
	}
        landunit = {
		id = { type = 22400 id = 55 }
		location = 1813
		name = "Virginia National Guard"
		division = {
			id = { type = 22400 id = 56 }
			name = "29th NG Infantry Division"
			strength = 100
			type = motorized
			model = 2
			}
	}
        landunit = {
		id = { type = 22400 id = 57 }
		location = 1847
		name = "Minnesota National Guard"
		division = {
			id = { type = 22400 id = 58 }
			name = "34th NG Infantry Division"
			strength = 100
			type = infantry
			model = 2
			}
	}
	landunit = {
		id = { type = 22400 id = 59 }
		location = 1914
		name = "Kansas National Guard"
		division = {
			id = { type = 22400 id = 60 }
			name = "35th NG Infantry Division"
			strength = 100
			type = infantry
			model = 2
			}
	}
	landunit = {
		id = { type = 22400 id = 61 }
		location = 1828
		name = "Indianapolis National Guard"
		division = {
			id = { type = 22400 id = 62 }
			name = "38th NG Infantry Division"
			strength = 100
			type = motorized
			model = 2
			}
	}
	landunit = {
		id = { type = 22400 id = 63 }
		location = 1887
		name = "Californa National Guard"
		division = {
			id = { type = 22400 id = 64 }
			name = "40th NG Infantry Division"
			strength = 100
			type = infantry
			model = 2
			}
	}
	landunit = {
		id = { type = 22400 id = 65 }
		location = 1795
		name = "New York National Guard"
		division = {
			id = { type = 22400 id = 66 }
			name = "42th NG Infantry Division"
			strength = 100
			type = motorized
			model = 2
			}
	}
        landunit = {
		id = { type = 22400 id = 67 }
		location = 1924
		name = "Texas National Guard"
		division = {
			id = { type = 22400 id = 68 }
			name = "49th NG Armored Division"  # became 46th inf in 2004
			strength = 100
			type = armor
			model = 15
      		}
	}
	landunit = {
		id = { type = 22400 id = 69 }
		location = 1734
		name = "Hawaii National Guard"
		division = {
			id = { type = 22400 id = 70 }
			name = "29th NG Infantry Brigade" # part of 40th NG division detached in hawaii
			strength = 100
			type = cavalry
			model = 2
		}
	}
	landunit = {
		id = { type = 22400 id = 90 }
		location = 1041
		name = "SOCOM"
		division = {
			experience = 15
			id = { type = 22400 id = 91 }
			name = "1st Special Forces Group"
			strength = 100
			type = bergsjaeger
			model = 14
			extra = engineer
			brigade_model = 4
		}
		division = {
			experience = 15
			id = { type = 22400 id = 92 }
			name = "3rd Special Forces Group"
			strength = 100
			type = bergsjaeger
			model = 14
			extra = engineer
			brigade_model = 4
		}
		division = {
			experience = 15
			id = { type = 22400 id = 93 }
			name = "5th Special Forces Group"
			strength = 100
			type = bergsjaeger
			model = 14
			extra = engineer
			brigade_model = 4
		}
		division = {
			experience = 15
			id = { type = 22400 id = 94 }
			name = "7th Special Forces Group"
			strength = 100
			type = bergsjaeger
			model = 14
			extra = engineer
			brigade_model = 4
		}
		division = {
			experience = 15
			id = { type = 22400 id = 95 }
			name = "10th Special Forces Group"
			strength = 100
			type = bergsjaeger
			model = 14
			extra = engineer
			brigade_model = 4
		}
	}
	landunit = {
		id = { type = 22400 id = 97 }
		location = 1809
		name = "National Guard Special Forces"
		division = {
			experience = 5
			id = { type = 22400 id = 98 }
			name = "19th NG Special Forces Group"
			strength = 100
			type = bergsjaeger
			model = 13
			extra = engineer
			brigade_model = 4
		}
		division = {
			experience = 5
			id = { type = 22400 id = 99 }
			name = "20th NG Special Forces Group"
			strength = 100
			type = bergsjaeger
			model = 13
			extra = engineer
			brigade_model = 4
		}
	}
 #    landunit = {
	#	id = { type = 22400 id = 619 }
	#	location = 1907
	#	name = "20th Air Force"
	#	division = {
	#		experience = 5
	#		id = { type = 22400 id = 620 }
	#		name = "90th Missile Wing"
	#		strength = 100
	#		type = flying_rocket
	#		model = 1
	#	}
	#	division = {
	#		experience = 5
	#		id = { type = 22400 id = 621 }
	#		name = "91st Missile Wing"
	#		strength = 100
	#		type = flying_rocket
	#		model = 1
	#	}
    #            division = {
	#		experience = 5
	#		id = { type = 22400 id = 622 }
	#		name = "341st Missile Wing"
	#		strength = 100
	#		type = flying_rocket
	#		model = 1
	#	}
	#}
	#########################################
	# marines needed for invasion of iraq
	# and transports, else doesn't happen
	# novapaddy
	#########################################
	   landunit = {
		id = { type = 22400 id = 3333 }
		location = 1683
		name = "101 Marine Division"
		division = {
			id = { type = 22400 id = 3334 }
			name = "1 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		division = {
			id = { type = 22400 id = 3335 }
			name = "2 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		}
	landunit = {
		id = { type = 22400 id = 3336 }
		location = 1812
		name = "102 Marine Division"
		division = {
			id = { type = 22400 id = 3337 }
			name = "3 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		division = {
			id = { type = 22400 id = 3338 }
			name = "4 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		}
	landunit = {
		id = { type = 22400 id = 3339 }
		location = 1812
		name = "103 Marine Division"
		division = {
			id = { type = 22400 id = 3340 }
			name = "5 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		division = {
			id = { type = 22400 id = 3341 }
			name = "6 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		}
	landunit = {
		id = { type = 22400 id = 3342 }
		location = 1734
		name = "104 Marine Division"
		division = {
			id = { type = 22400 id = 3343 }
			name = "7 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		division = {
			id = { type = 22400 id = 3344 }
			name = "8 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		}
	landunit = {
		id = { type = 22400 id = 3345 }
		location = 1886
		name = "105 Marine Division"
		division = {
			id = { type = 22400 id = 3346 }
			name = "9 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		division = {
			id = { type = 22400 id = 3347 }
			name = "10 Marine Division"
			strength = 100
			type = marine
			model = 17
			}
		}
	navalunit = {
		id = { type = 22400 id = 3348 }
		location = 1812
		base = 1812
		name = "Free Kuwait Group"
		division = {
			id = { type = 22400 id = 3349 }
			name = "USS Kuwait"
			type = transport
			model = 4
		}
		division = {
			id = { type = 22400 id = 3350 }
			name = "Transport Fleet - Kuwait"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 3351 }
			name = "Transport Fleet - Basra"
			type = transport
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 3352 }
		location = 1734
		base = 1734
		name = "Free Kuwait Group 2"
		division = {
			id = { type = 22400 id = 3353 }
			name = "USS Saud"
			type = transport
			model = 4
		}
		division = {
			id = { type = 22400 id = 3354 }
			name = "Transport Fleet - Kuwait2"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 3355 }
			name = "Transport Fleet - Basra2"
			type = transport
			model = 3
		}
	}
	# #####################################
	# NAVY
	# ######################################
	navalunit = {
		id = { type = 22400 id = 300 }
		location = 1809
		base = 1809
		name = "Kitty Hawk Strike Group"
		division = {
			id = { type = 22400 id = 301 }
			name = "USS Kitty Hawk"
			type = carrier
			model = 0
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 302 }
			name = "USS Chansellorsville"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 303 }
			name = "USS Cowpens"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 304 }
			name = "USS Vincennes"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 305 }
			name = "USS John S. McCain"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 306 }
			name = "USS Cushing"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 307 }
			name = "USS O'Brien"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 308 }
			name = "USS Vandegrift"
			type = destroyer
			model = 2
		}
		division = {
			id = { type = 22400 id = 309 }
			name = "USS Gary"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 310 }
			name = "USS Curtis Wilbur"
			type = light_cruiser
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 311 }
		location = 2212
		base = 1041
		name = "John F. Kennedy Strike Group"
		division = {
			id = { type = 22400 id = 312 }
			name = "USS John F. Kennedy"
			type = carrier
			model = 0
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 313 }
			name = "USS Vicksburg"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 314 }
			name = "USS Hué City"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 315 }
			name = "USS Monterey"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 316 }
			name = "USS Roosevelt"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 317 }
			name = "USS Carney"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 318 }
			name = "USS The Sullivans"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 319 }
			name = "USS Spruance"
			type = light_cruiser
			model = 1
		}
		division = {
			id = { type = 22400 id = 320 }
			name = "USS O'Bannon"
			type = light_cruiser
			model = 1
		}
		division = {
			id = { type = 22400 id = 321 }
			name = "USS Underwood"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 322 }
			name = "USS Estocin"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 323 }
			name = "USS McInerney"
			type = destroyer
			model = 5
		}
		division = {
			id = { type = 22400 id = 324 }
			name = "USS Doyle"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 325 }
			name = "USS Klakring"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 326 }
			name = "USS Robert G. Bradley"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 327 }
			name = "USS Taylor"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 328 }
			name = "USS Simpson"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 329 }
			name = "USS Boone"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 330 }
		location = 1812
		base = 1812
		name = "Theodore Roosevelt Strike Group"
		division = {
			id = { type = 22400 id = 331 }
			name = "USS Theodore Roosevelt"
			type = carrier
			model = 2
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 332 }
			name = "USS Cape St. George"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 333 }
			name = "USS Anzio"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 334 }
			name = "USS Leyte Gulf"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 335 }
			name = "USS Vella Gulf"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 336 }
			name = "USS Winston S. Churchill"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 337 }
			name = "USS Mitscher"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 338 }
			name = "USS Porter"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 339 }
			name = "USS Ramage"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 340 }
			name = "USS Ross"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 341 }
			name = "USS Hayler"
			type = light_cruiser
			model = 1
		}
		division = {
			id = { type = 22400 id = 342 }
			name = "USS Stump"
			type = light_cruiser
			model = 1
		}
		division = {
			id = { type = 22400 id = 343 }
			name = "USS Deyo"
			type = light_cruiser
			model = 1
		}
		division = {
			id = { type = 22400 id = 344 }
			name = "USS Halyburton"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 345 }
			name = "USS Elrod"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 346 }
			name = "USS Carr"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 347 }
			name = "USS De Wert"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 348 }
		location = 1812
		base = 1812
		name = "Harry S. Truman Strike Group"
		division = {
			id = { type = 22400 id = 349 }
			name = "USS Harry S. Truman"
			type = carrier
			model = 2
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 350 }
			name = "USS San Jacinto"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 351 }
			name = "USS Donald Cook"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 352 }
			name = "USS Oscar Austin"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 353 }
			name = "USS Cole"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 354 }
			name = "USS Briscoe"
			type = light_cruiser
			model = 1
		}
		division = {
			id = { type = 22400 id = 355 }
			name = "USS Hawes"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 356 }
		location = 1812
		base = 1812
		name = "Enterprise Strike Group"
		division = {
			id = { type = 22400 id = 357 }
			name = "USS Enterprise"
			type = carrier
			model = 1
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 358 }
			name = "USS Philippine Sea"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 359 }
			name = "USS Gettysburg"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 360 }
			name = "USS Stout"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 361 }
			name = "USS Gonzalez"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 362 }
			name = "USS McFaul"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 363 }
			name = "USS Thorn"
			type = light_cruiser
			model = 1
		}
		division = {
			id = { type = 22400 id = 364 }
			name = "USS Nicholas"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 365 }
		location = 1812
		base = 1812
		name = "George Washington Strike Group"
		division = {
			id = { type = 22400 id = 366 }
			name = "USS George Washington"
			type = carrier
			model = 2
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 367 }
			name = "USS Normandy"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 368 }
			name = "USS Mason"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 369 }
			name = "USS Arleigh Burke"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 370 }
			name = "USS Bulkeley"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 371 }
			name = "USS Laboon"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 372 }
			name = "USS Barry"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 373 }
			name = "USS Mahan"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 374 }
			name = "USS Kauffman"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 375 }
			name = "USS Samuel B. Roberts"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 376 }
		location = 1812
		base = 1812
		name = "Dwight D. Eisenhower Strike Group"
		division = {
			id = { type = 22400 id = 377 }
			name = "USS Dwight D. Eisenhower"
			type = carrier
			model = 2
			strength = 25
			extra = cag
			brigade_model = 2
		}
	}
	navalunit = {
		id = { type = 22400 id = 388 }
		location = 2212
		base = 1041
		name = "Amphibious Group Two"
		division = {
			id = { type = 22400 id = 389 }
			name = "USS Wasp"
			type = transport
			model = 4
		}
		division = {
			id = { type = 22400 id = 390 }
			name = "USS Bataan"
			type = transport
			model = 4
		}
		division = {
			id = { type = 22400 id = 391 }
			name = "USS Iwo Jima"
			type = transport
			model = 4
		}
		division = {
			id = { type = 22400 id = 392 }
			name = "USS Kearsage"
			type = transport
			model = 4
		}
		division = {
			id = { type = 22400 id = 393 }
			name = "USS Saipan"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 394 }
			name = "USS Nassau"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 395 }
			name = "Transport Fleet - Austin"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 396 }
			name = "Transport Fleet - Shreveport"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 397 }
			name = "Transport Fleet - Nashville"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 398 }
			name = "Transport Fleet - Trenton"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 399 }
			name = "Transport Fleet - Ponce"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 400 }
			name = "Transport Fleet - San Antonio"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 401 }
			name = "Transport Fleet - Whidbey Island"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 402 }
			name = "Transport Fleet - Fort McHenry"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 403 }
			name = "Transport Fleet - Ashland"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 404 }
			name = "Transport Fleet - Carter Hall"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 405 }
			name = "Transport Fleet - Oak Hill"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 406 }
			name = "Transport Fleet - Mount Whitney"
			type = transport
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 407 }
		location = 1874
		base = 1874
		name = "Abraham Lincoln Strike Group"
		division = {
			id = { type = 22400 id = 408 }
			name = "USS Abraham Lincoln"
			type = carrier
			model = 2
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 409 }
			name = "USS Shiloh"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 410 }
			name = "USS Bunker Hill"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 411 }
			name = "USS Shoup"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 412 }
			name = "USS Preble"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 413 }
			name = "USS Ford"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 414 }
			name = "USS Ingraham"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 415 }
			name = "USS Rodney M. Davis"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 416 }
		location = 1886
		base = 1886
		name = "Nimitz Strike Group"
		division = {
			id = { type = 22400 id = 417 }
			name = "USS Nimitz"
			type = carrier
			model = 2
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 418 }
			name = "USS Mobile Bay"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 419 }
			name = "USS McCampbell"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 420 }
			name = "USS Curts"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 421 }
		location = 1886
		base = 1886
		name = "Carl Vinson Strike Group"
		division = {
			id = { type = 22400 id = 422 }
			name = "USS Carl Vinson"
			type = carrier
			model = 2
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 423 }
			name = "USS Antietam"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 424 }
			name = "USS Princeton"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 425 }
			name = "USS Lassen"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 426 }
			name = "USS Frizgerald"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 427 }
			name = "USS Decatur"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 428 }
			name = "USS Oldendorf"
			type = light_cruiser
			model = 1
		}
		division = {
			id = { type = 22400 id = 429 }
			name = "USS Thach"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 430 }
		location = 1886
		base = 1886
		name = "Stennis Strike Group"
		division = {
			id = { type = 22400 id = 431 }
			name = "USS John C. Stennis"
			type = carrier
			model = 2
			extra = cag
			brigade_model = 1
		}
		division = {
			id = { type = 22400 id = 432 }
			name = "USS Port Royal"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 433 }
			name = "USS Lake Champlain"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 434 }
			name = "USS Valley Forge"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 435 }
			name = "USS Stethem"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 436 }
			name = "USS Higgins"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 437 }
			name = "USS Elliot"
			type = light_cruiser
			model = 1
		}
		division = {
			id = { type = 22400 id = 438 }
			name = "USS Jarrett"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 439 }
			name = "USS Rentz"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 440 }
		location = 1886
		base = 1886
		name = "Constellation Strike Group"
		division = {
			id = { type = 22400 id = 441 }
			name = "USS Constellation"         # decommissioned 6th august
			type = carrier
			model = 0
			extra = cag
			brigade_model = 2
		}
		division = {
			id = { type = 22400 id = 442 }
			name = "USS Lake Erie"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 443 }
			name = "USS Chosin"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 444 }
			name = "USS Howard"
			type = light_cruiser
			model = 3
		}
		division = {
			id = { type = 22400 id = 445 }
			name = "USS John Paul Jones"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 446 }
			name = "USS Benford"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 447 }
			name = "USS Milius"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 448 }
			name = "USS McClusky"
			type = destroyer
			model = 2
		}
	}
	navalunit = {
		id = { type = 22400 id = 456 }
		location = 1886
		base = 1886
		name = "Amphibious Group Tree"
		division = {
			id = { type = 22400 id = 457 }
			name = "USS Boxer"
			type = transport
			model = 4
		}
		division = {
			id = { type = 22400 id = 458 }
			name = "USS Bonhomme Richard"
			type = transport
			model = 4
		}
		division = {
			id = { type = 22400 id = 459 }
			name = "USS Tarawa"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 460 }
			name = "USS Belleau Wood"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 461 }
			name = "USS Peleliu"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 462 }
			name = "Transport Fleet - Comstock"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 463 }
			name = "Transport Fleet - Rushmore"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 464 }
			name = "Transport Fleet - Ogden"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 465 }
			name = "Transport Fleet - Duluth"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 466 }
			name = "Transport Fleet - Cleveland"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 467 }
			name = "Transport Fleet - Denver"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 468 }
			name = "Transport Fleet - Juneau"
			type = transport
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 469 }
		location = 1683
		base = 1683
		name = "Essex Amphibious Ready Group"
		division = {
			id = { type = 22400 id = 470 }
			name = "USS Essex"
			type = transport
			model = 4
		}
		division = {
			id = { type = 22400 id = 471 }
			name = "Transport Fleet - Anchorage"
			type = transport
			model = 3
		}
		division = {
			id = { type = 22400 id = 472 }
			name = "Transport Fleet - Mount Vernon"
			type = transport
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 473 }
		location = 1563
		base = 1563
		name = "Destroyer Squadron Six"
		division = {
			id = { type = 22400 id = 474 }
			name = "USS Ticonderoga"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 475 }
			name = "USS Yorktown"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 476 }
			name = "USS Thomas S. Gates"
			type = battlecruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 477 }
			name = "USS Stephen W. Groves"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 478 }
			name = "USS John L. Hall"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 479 }
		location = 1734
		base = 1734
		name = "Destroyer Squadron Thirty-One"
		division = {
			id = { type = 22400 id = 480 }
			name = "USS Russel"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 481 }
			name = "USS Paul Hamilton"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 482 }
			name = "USS Hopper"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 483 }
			name = "USS O'Kane"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 484 }
			name = "USS Fletcher"
			type = light_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 485 }
			name = "USS Crommelin"
			type = destroyer
			model = 3
		}
		division = {
			id = { type = 22400 id = 486 }
			name = "USS Reuben James"
			type = destroyer
			model = 3
		}
	}
	navalunit = {
		id = { type = 22400 id = 487 }
		location = 1734
		base = 1734
		name = "Submarine Squadron One"
		division = {
			id = { type = 22400 id = 488 }
			name = "USS Los Angeles"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 489 }
			name = "USS La Jolla"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 490 }
			name = "USS San Francisco"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 491 }
			name = "USS Buffalo"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 492 }
			name = "USS Charlotte"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 493 }
			name = "USS Greeneville"
			type = submarine
			model = 15
		}
	}
	navalunit = {
		id = { type = 22400 id = 494 }
		location = 1734
		base = 1734
		name = "Submarine Squadron Three"
		division = {
			id = { type = 22400 id = 495 }
			name = "USS Olympia"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 496 }
			name = "USS Honolulu"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 497 }
			name = "USS Chicago"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 498 }
			name = "USS Key West"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 499 }
			name = "USS Louisville"
			type = submarine
			model = 4
		}
		division = {
			id = { type = 22400 id = 500 }
			name = "USS Asheville"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 501 }
			name = "USS Columbia"
			type = submarine
			model = 15
		}
	}
	navalunit = {
		id = { type = 22400 id = 502 }
		location = 1734
		base = 1734
		name = "Submarine Squadron Seven"
		division = {
			id = { type = 22400 id = 503 }
			name = "USS Pasadena"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 504 }
			name = "USS Topeka"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 505 }
			name = "USS Columbus"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 506 }
			name = "USS Santa Fe"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 507 }
			name = "USS Cheyenne"
			type = submarine
			model = 15
		}
	}
	navalunit = {
		id = { type = 22400 id = 508 }
		location = 1683
		base = 1683
		name = "Submarine Squadron Fifteen"
		division = {
			id = { type = 22400 id = 509 }
			name = "USS City of Corpus Christi"
			type = submarine
			model = 14
		}
	}
	navalunit = {
		id = { type = 22400 id = 510 }
		location = 1789
		base = 1789
		name = "Submarine Squadron Two"
		division = {
			id = { type = 22400 id = 511 }
			name = "USS Dallas"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 512 }
			name = "USS Alberquerque"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 513 }
			name = "USS Pittsburgh"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 514 }
			name = "USS Springfield"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 515 }
			name = "USS Toledo"
			type = submarine
			model = 15
		}
	}
	navalunit = {
		id = { type = 22400 id = 516 }
		location = 1789
		base = 1789
		name = "Submarine Squadron Four"
		division = {
			id = { type = 22400 id = 517 }
			name = "USS Providence"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 518 }
			name = "USS Miami"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 519 }
			name = "USS Annapolis"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 520 }
			name = "USS Hartford"
			type = submarine
			model = 15
		}
	}
	navalunit = {
		id = { type = 22400 id = 521 }
		location = 1789
		base = 1789
		name = "Submarine Squadron Eigth"
		division = {
			id = { type = 22400 id = 522 }
			name = "USS Oklahoma City"
			type = submarine
			model = 14
		}
	}
	navalunit = {
		id = { type = 22400 id = 523 }
		location = 1789
		base = 1789
		name = "Submarine Development Squadron Twelve"
		division = {
			id = { type = 22400 id = 524 }
			name = "USS Philadelphia"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 525 }
			name = "USS Augusta"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 526 }
			name = "USS San Juan"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 527 }
			name = "USS Alexandria"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 528 }
			name = "USS Memphis"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 529 }
			name = "USS Seawolf"
			type = submarine
			model = 16
		}
		division = {
			id = { type = 22400 id = 530 }
			name = "USS Connecticut"
			type = submarine
			model = 16
		}
	}
	navalunit = {
		id = { type = 22400 id = 449 }
		location = 1886
		base = 1886
		name = "Submarine Squadron Eleven"
		division = {
			id = { type = 22400 id = 450 }
			name = "USS Bremerton"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 451 }
			name = "USS Portsmouth"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 452 }
			name = "USS Houston"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 453 }
			name = "USS Salt Lake City"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 454 }
			name = "USS Helena"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 455 }
			name = "USS Jefferson City"
			type = submarine
			model = 15
		}
	}
	navalunit = {
		id = { type = 22400 id = 378 }
		location = 1812
		base = 1812
		name = "Submarine Squadron Six"
		division = {
			id = { type = 22400 id = 379 }
			name = "USS Montpelier"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 380 }
			name = "USS Norfolk"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 381 }
			name = "USS Minneapolis-Saint Paul"
			type = submarine
			model = 14
		}
	}
	navalunit = {
		id = { type = 22400 id = 382 }
		location = 1812
		base = 1812
		name = "Submarine Squadron Eight"
		division = {
			id = { type = 22400 id = 383 }
			name = "USS Jacksonville"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 384 }
			name = "USS Hyman G. Rickover"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 385 }
			name = "USS Newport News"
			type = submarine
			model = 14
		}
		division = {
			id = { type = 22400 id = 386 }
			name = "USS Boise"
			type = submarine
			model = 15
		}
		division = {
			id = { type = 22400 id = 387 }
			name = "USS Hampton"
			type = submarine
			model = 15
		}
	}
	navalunit = {
		id = { type = 22400 id = 531 }
		location = 1789
		base = 1789
		name = "Groton SSGN Command"
		division = {
			id = { type = 22400 id = 532 }
			name = "USS Ohio"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 533 }
			name = "USS Florida"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 534 }
			name = "USS Henry M. Jackson"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 535 }
			name = "USS Alabama"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 536 }
			name = "USS Nevada"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 537 }
			name = "USS Pennsylvania"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 538 }
			name = "USS Kentucky"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 539 }
			name = "USS Nebraska"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 540 }
			name = "USS Maine"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 541 }
			name = "USS Louisiana"
			type = heavy_cruiser
			model = 2
		}
	}
	navalunit = {
		id = { type = 22400 id = 542 }
		location = 1952
		base = 1952
		name = "Submarine Group Ten"
		division = {
			id = { type = 22400 id = 543 }
			name = "USS Michigan"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 544 }
			name = "USS Georgia"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 545 }
			name = "USS Alaska"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 546 }
			name = "USS Tennessee"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 547 }
			name = "USS West Virginia"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 548 }
			name = "USS Maryland"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 549 }
			name = "USS Rhode Island"
			type = heavy_cruiser
			model = 2
		}
		division = {
			id = { type = 22400 id = 550 }
			name = "USS Wyoming"
			type = heavy_cruiser
			model = 2
		}
	}
	# #####################################
	# AIR FORCE
	# #####################################
	airunit = {
		id = { type = 22400 id = 100 }
		location = 1930
		base = 1930
		name = "8th Air Force"
		division = {
			id = { type = 22400 id = 101 }
			name = "2d Bomb Wing"
			type = strategic_bomber
			strength = 100
			model = 1
		}
		division = {
			id = { type = 22400 id = 102 }
			name = "5th Bomb Wing"
			type = strategic_bomber
			strength = 100
			model = 1
		}
                division = {
			id = { type = 22400 id = 103 }
			name = "131st Bomb Wing"
			type = strategic_bomber
			strength = 100
			model = 5
		}
		division = {
			id = { type = 22400 id = 104 }
			name = "509th Bomb Wing"        # iraq
			type = strategic_bomber
			strength = 100
			model = 5
		}
	}
        airunit = {
		id = { type = 22400 id = 105 }
		location = 1957
		base = 1957
		name = "9th Air Force"
		division = {
			id = { type = 22400 id = 106 }
			name = "1st Fighter Wing"
			type = multi_role
			strength = 100
			model = 3
		}
		division = {
			id = { type = 22400 id = 107 }
			name = "4th Fighter Wing"
			type = tactical_bomber
			strength = 100
			model = 3
		}
                division = {
			id = { type = 22400 id = 108 }
			name = "20th Fighter Wing"
			type = interceptor
			strength = 100
			model = 3
		}
                division = {
			id = { type = 22400 id = 109 }
			name = "33d Fighter Wing"        
			type = multi_role
			strength = 100
			model = 3
		}
	}
        airunit = {
		id = { type = 22400 id = 110 }
		location = 1901
		base = 1901
		name = "12th Air Force"
		division = {
			id = { type = 22400 id = 111 }
			name = "7th Bomb Wing"
			type = strategic_bomber
			strength = 100
			model = 2
		}
		division = {
			id = { type = 22400 id = 112 }
			name = "28th Bomb Wing"
			type = strategic_bomber
			strength = 100
			model = 2
		}
                division = {
			id = { type = 22400 id = 113 }
			name = "49th Fighter Wing"
			type = tactical_bomber # f-117
			strength = 100
			model = 6
		}
                division = {
			id = { type = 22400 id = 114 }
			name = "355th Fighter Wing"        
			type = cas
			strength = 100
			model = 0
		}
                division = {
			id = { type = 22400 id = 115 }
			name = "366th Fighter Wing"        
			type = multi_role
			strength = 100
			model = 3
		}
                division = {
			id = { type = 22400 id = 116 }
			name = "388th Fighter Wing"        
			type = interceptor
			strength = 100
			model = 3
		}
	}
        airunit = {
		id = { type = 22400 id = 117 }
		location = 130
		base = 130
		name = "3rd Air Force - Germany"
		division = {
			id = { type = 22400 id = 118 }
			name = "52d Fighter Wing"
			type = interceptor
			strength = 100
			model = 3
		}
		division = {
			id = { type = 22400 id = 119 }
			name = "86th Air Wing"
			type = transport_plane
			strength = 100
			model = 1
		}
	}
        airunit = {
		id = { type = 22400 id = 120 }
		location = 25
		base = 25
		name = "3rd Air Force - UK"
		division = {
			id = { type = 22400 id = 121 }
			name = "48th Fighter Wing"
			type = tactical_bomber
			strength = 100
			model = 3
		}
	}
        airunit = {
		id = { type = 22400 id = 122 }
		location = 405
		base = 405
		name = "3rd Air Force - Italy"
		division = {
			id = { type = 22400 id = 123 }
			name = "31st Fighter Wing"
			type = interceptor
			strength = 100
			model = 3
		}
	}
        airunit = {
		id = { type = 22400 id = 124 }
		location = 1552
		base = 1552
		name = "5th Air Force"
		division = {
			id = { type = 22400 id = 125 }
			name = "18th Wing"
			type = multi_role
			strength = 100
			model = 3
		}
                division = {
			id = { type = 22400 id = 126 }
			name = "35th Fighter Wing"
			type = interceptor
			strength = 100
			model = 3
		}
                division = {
			id = { type = 22400 id = 127 }
			name = "374th Airlift Wing"
			type = transport_plane
			strength = 100
			model = 1
		}
	}
        airunit = {
		id = { type = 22400 id = 128 }
		location = 1228
		base = 1228
		name = "7th Air Force"
		division = {
			id = { type = 22400 id = 129 }
			name = "8th Fighter Wing"
			type = interceptor
			strength = 100
			model = 3
		}
                division = {
			id = { type = 22400 id = 130 }
			name = "51st Fighter Wing"
			type = interceptor
			strength = 100
			model = 3
		}
	}
        airunit = {
		id = { type = 22400 id = 131 }
		location = 2142
		base = 2142
		name = "11th Air Force"
		division = {
			id = { type = 22400 id = 132 }
			name = "3d Wing"
			type = multi_role
			strength = 100
			model = 3
		}
                division = {
			id = { type = 22400 id = 133 }
			name = "354th Fighter Wing"
			type = interceptor
			strength = 100
			model = 3
		}
	}
        airunit = {
		id = { type = 22400 id = 134 }
		location = 1734
		base = 1734
		name = "13th Air Force"
		division = {
			id = { type = 22400 id = 135 }
			name = "15th Airlift Wing"
			type = transport_plane
			strength = 100
			model = 2
		}
	}
        airunit = {
		id = { type = 22400 id = 136 }
		location = 1829
		base = 1829
		name = "18th Air Force"   # i put only a litte part of transport wings if i put it all then they should be around 30..
		division = {
			id = { type = 22400 id = 137 }
			name = "6th Air Mobility Wing"
			type = transport_plane
			strength = 100
			model = 2
		}
                division = {
			id = { type = 22400 id = 138 }
			name = "60th Air Mobility Wing"
			type = transport_plane
			strength = 100
			model = 2
		}
                division = {
			id = { type = 22400 id = 139 }
			name = "305th Air Mobility Wing"
			type = transport_plane
			strength = 100
			model = 2
		}
                division = {
			id = { type = 22400 id = 140 }
			name = "43rd Airlift Wing"
			type = transport_plane
			strength = 100
			model = 1
		}
                division = {
			id = { type = 22400 id = 141 }
			name = "62nd Airlift Wing"
			type = transport_plane
			strength = 100
			model = 2
		}
                division = {
			id = { type = 22400 id = 142 }
			name = "89th Airlift Wing"
			type = transport_plane
			strength = 100
			model = 2
		}
                division = {
			id = { type = 22400 id = 143 }
			name = "375th Airlift Wing"
			type = transport_plane
			strength = 100
			model = 2
		}
                division = {
			id = { type = 22400 id = 144 }
			name = "436th Airlift Wing"
			type = transport_plane
			strength = 100
			model = 2
		}
                division = {
			id = { type = 22400 id = 145 }
			name = "437th Airlift Wing"
			type = transport_plane
			strength = 100
			model = 2
		}
	}
        airunit = {
		id = { type = 22400 id = 146 }
		location = 1924
		base = 1924
		name = "10th Air Force"  # us air force reserve
		division = {
			id = { type = 22400 id = 147 }
			name = "301st Fighter Wing"
			type = interceptor
			strength = 20
			model = 2
		}
                division = {
			id = { type = 22400 id = 148 }
			name = "419th Fighter Wing"
			type = interceptor
			strength = 20
			model = 2
		}
                division = {
			id = { type = 22400 id = 149 }
			name = "442nd Fighter Wing"
			type = cas
			strength = 20
			model = 0
		}
                division = {
			id = { type = 22400 id = 150 }
			name = "482nd Fighter Wing"
			type = interceptor
			strength = 20
			model = 2
		}
                division = {
			id = { type = 22400 id = 151 }
			name = "944th Fighter Wing"
			type = interceptor
			strength = 20
			model = 2
		}
	}
        airunit = {
		id = { type = 22400 id = 152 }
		location = 1734
		base = 1734
		name = "Patrol Wing 2"  
		division = {
			id = { type = 22400 id = 153 }
			name = "Patrol Wing 2"
			type = naval_bomber
			strength = 100
			model = 2
		}
	}
        airunit = {
		id = { type = 22400 id = 154 }
		location = 1874
		base = 1874
		name = "Patrol Wing 10"  
		division = {
			id = { type = 22400 id = 155 }
			name = "Patrol Wing 10"
			type = naval_bomber
			strength = 100
			model = 2
		}
	}
        airunit = {
		id = { type = 22400 id = 156 }
		location = 1952
		base = 1952
		name = "Patrol Wing 11"  
		division = {
			id = { type = 22400 id = 157 }
			name = "Patrol Wing 11"
			type = naval_bomber
			strength = 100
			model = 2
		}
	}
        airunit = {
		id = { type = 22400 id = 158 }
		location = 1563
		base = 1563
		name = "III Marine Expeditionary Force"  
		division = {
			id = { type = 22400 id = 159 }
			name = "1st Marine Aircraft Wing"
			type = interceptor
			strength = 100
			model = 2
		}
	}
        airunit = {
		id = { type = 22400 id = 160 }
		location = 1963
		base = 1963
		name = "II Marine Expeditionary Force"  
		division = {
			id = { type = 22400 id = 161 }
			name = "2nd Marine Aircraft Wing"
			type = interceptor
			strength = 100
			model = 2
		}
	}
        airunit = {
		id = { type = 22400 id = 162 }
		location = 1041
		base = 1041
		name = "I Marine Expeditionary Force"  
		division = {
			id = { type = 22400 id = 163 }
			name = "3rd Marine Aircraft Wing"
			type = interceptor
			strength = 60
			model = 2
		}
	}
        airunit = {
		id = { type = 22400 id = 164 }
		location = 1931
		base = 1931
		name = "Marine Force Reserve"  
		division = {
			id = { type = 22400 id = 165 }
			name = "4th Marine Aircraft Wing"
			type = interceptor
			strength = 100
			model = 2
		}
	}
	# ###################################
	# Under Development
	# ###################################
	division_development = {
		id = { type = 22400 id = 600 }
		name = "USS Ronald Reagan"
		type = carrier
		model = 2
		cost = 15
		date = { day = 10 month = october year = 2003 }
	}
	division_development = {
		id = { type = 22400 id = 601 }
		name = "USS Momsen"
		type = light_cruiser
		model = 3
		cost = 5
		date = { day = 17 month = march year = 2004 }
	}
        division_development = {
		id = { type = 22400 id = 602 }
		name = "USS Jimmy Carter"
		type = submarine
		model = 16
		cost = 5
		date = { day = 1 month = may year = 2004 }
	}
	division_development = {
		id = { type = 22400 id = 603 }
		name = "USS Virginia"
		type = submarine
		model = 16
		cost = 5
		date = { day = 1 month = may year = 2004 }
	}
	division_development = {
		id = { type = 22400 id = 604 }
		name = "USS Chung-Hoon"
		type = light_cruiser
		model = 3
		cost = 5
		date = { day = 13 month = september year = 2004 }
	}
	division_development = {
		id = { type = 22400 id = 605 }
		name = "USS Nitze"
		type = light_cruiser
		model = 3
		cost = 5
		date = { day = 12 month = january year = 2005 }
	}
	division_development = {
		id = { type = 22400 id = 606 }
		name = "USS James E. Williams"
		type = light_cruiser
		model = 3
		cost = 5
		date = { day = 22 month = april year = 2005 }
	}
	division_development = {
		id = { type = 22400 id = 607 }
		name = "USS Bainbridge"
		type = light_cruiser
		model = 3
		cost = 5
		date = { day = 20 month = august year = 2005 }
	}
	division_development = {
		id = { type = 22400 id = 608 }
		name = "USS Halsey"
		type = light_cruiser
		model = 3
		cost = 5
		date = { day = 4 month = november year = 2005 }
	}
	division_development = {
		id = { type = 22400 id = 609 }
		name = "USS Texas"
		type = submarine
		model = 16
		cost = 5
		date = { day = 8 month = june year = 2005 }
	}
	division_development = {
		id = { type = 22400 id = 610 }
		name = "USS Forrest Sherman"
		type = light_cruiser
		model = 3
		cost = 5
		date = { day = 21 month = february year = 2006 }
	}
	division_development = {
		id = { type = 22400 id = 611 }
		name = "USS Farragut"
		type = light_cruiser
		model = 3
		cost = 5
		date = { day = 2 month = july year = 2006 }
	}
	division_development = {
		id = { type = 22400 id = 612 }
		name = "USS Makin Island"
		type = transport
		model = 4
		cost = 10
		date = { day = 26 month = may year = 2006 }
	}
	division_development = {
		id = { type = 22400 id = 614 }
		name = "USS Hawaii"
		type = submarine
		model = 16
		cost = 5
		date = { day = 25 month = may year = 2007 }
	}
	division_development = {
		id = { type = 22400 id = 615 }
		name = "USS George H.W. Bush"
		type = carrier
		model = 2
		cost = 40
		date = { day = 3 month = august year = 2008 }
	}
	division_development = {
		id = { type = 22400 id = 616 }
		name = "USS North Carolina"
		type = submarine
		model = 16
		cost = 5
		date = { day = 17 month = june year = 2008 }
	}
}
