 
 ############################## 
 # Country definition for U55 # 
 ############################## 
  
 country = 
 {  tag                    = U55 
   # Resource Reserves 
energy                 = 300
metal                  = 150
rare_materials         = 75
   oil                    = 500 
   supplies               = 500 
   money                  = 10 
   manpower               = 0 
   capital                = 863 
   diplomacy = 
   {  relation = {  tag = BEL value = 200  } 
     relation = {  tag = DEN value = 100  } 
     relation = {  tag = FIN value = 100  } 
     relation = {  tag = FRA value = 120  } 
     relation = {  tag = GER value = -50  } 
     relation = {  tag = HOL value = 150  } 
     relation = {  tag = IRE value = 75  } 
     relation = {  tag = NOR value = 100  } 
     relation = {  tag = SWE value = 100  } 
    } 
   SpyInfo                = {  country = "U55" NumberOfSpies = 3  } 
   nationalprovinces      = {  859 860 861 862 863 865  } 
   ownedprovinces         = {  859 860 861 862 863 865  } 
   controlledprovinces    = {  859 860 861 862 863 865  }  
   techapps = {
		# Industry
		5010 5020
		5030 5040
		5050 5060
		5070 5080
		5090 5110
		5120 5130
		5140 5150
		5160 5170
		5180 5190
		# Army Equip
		2200 2210
		2600 2610
		2800 2810
		2700 2710
		2000 2010
		2500 2510
		2300 2310
		2400 2410
		# Army Org
		1970 1980
		1260 1900
		1910 1800
		1700 1000
		1010 1500
		1510 1400
		1410 1300
		1310 1200
		1210 # Aircraft
		4700 4710
		4750 4760
		4800 4900
		4000 4010
		4020 4640
		4650 # Land Docs
		6910 6600
		6610 6010
		6020 6100
		6110 6120
		6140 6150
		6160 6170
	}
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 9 
     political_left    = 1 
     freedom           = 9 
     free_market       = 8 
     professional_army = 1 
     defense_lobby     = 2 
     interventionism   = 1 
    } 
   
  } 
 
